export type JobRecordAction = 'brief' | 'propose' | 'assign' | 'deliver' | 'accept' | 'cancel';
export type JobReward = { asset: 'proofs'; amountSats: string } | { asset: 'WORK'; token: string; amountSubatoms: string };
export const JOBS_BODY_PREFIX: string;
export const JOBS_VERSION: number;
export const JOBS_SUPPORTED_VERSIONS: readonly number[];
export const JOBS_ACTIVATION_HEIGHT: number;
export const JOBS_ACTIVATION_PREVIOUS_BLOCK_HASH: string;
export const JOBS_V2_ACTIVATION_HEIGHT: number;
export const JOBS_V2_ACTIVATION_PREVIOUS_BLOCK_HASH: string;
export const JOBS_WORK_TOKEN_ID: string;
export const JOBS_WORK_REGISTRY_ADDRESS: string;
export const JOBS_WORK_SUBATOMS_PER_WORK: string;
export const JOBS_WORK_MAX_SUBATOMS: string;
export function normalizeJobReward(value: unknown): JobReward | null;
export const parseJobReward: typeof normalizeJobReward;
export function jobRewardFromMetadata(metadata: unknown): JobReward | null;
export function parseJobWorkDecimal(value: string): string | null;
export function formatJobWorkSubatoms(value: string): string;
export function formatJobReward(value: JobReward): string;
export const JOBS_MAX_METADATA_BYTES: number;
export const JOBS_ACTIONS: readonly JobRecordAction[];
export function encodeJobRecord(action: JobRecordAction, value: Record<string, unknown>): string;
export function parseJobBody(body: string): { action: JobRecordAction; metadata: Record<string, unknown> } | null;
