[Service]
LimitCORE=0
NoNewPrivileges=true
ProtectHome=true
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=
AmbientCapabilities=CAP_NET_BIND_SERVICE
RestrictSUIDSGID=true
LockPersonality=true
PrivateDevices=true
ProtectControlGroups=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
RestrictRealtime=true
SystemCallArchitectures=native
