/data/mempool/nginx-logs/access_mempool.log /data/mempool/nginx-logs/error_mempool.log {
    size 100M
    rotate 14
    missingok
    notifempty
    compress
    create 0640 1000 1000
    sharedscripts
    postrotate
        /usr/bin/docker exec mempool-web-1 nginx -s reopen
    endscript
}
