[Interface]
Address = 10.77.0.2/30
ListenPort = 51820
PostUp = /usr/bin/wg set %i private-key /etc/wireguard/privatekey

[Peer]
PublicKey = S2n5vA3b6IHHE9LWy4RSnOMYtysLWuxhMeRPHNVQx3I=
AllowedIPs = 10.77.0.1/32
Endpoint = 77.42.91.106:51820
PersistentKeepalive = 25
