[Interface]
Address = 10.77.0.1/30
ListenPort = 51820
PostUp = /usr/bin/wg set %i private-key /etc/wireguard/privatekey

[Peer]
PublicKey = aYS7qIGkz2R2+3KexhiM3WdOFGsig40DB9BjcK1l9wo=
AllowedIPs = 10.77.0.2/32
Endpoint = 65.108.122.87:51820
PersistentKeepalive = 25
