export type GrowthForecastHorizon = { label: string; years: number; adoption: number };
export type BoostGrowthModelInputs = {
  bitnodesReachableNodes: number;
  agentShare: number;
  nodeCagr: number;
  currentBtcUsd: number;
  historicalBtcUsd: number;
  btcBenchmarkYears: number;
  currentPowids: number;
  idDensitySatsPerN2: number;
  baselineMailFlowSats: number;
  baselineFileFlowSats: number;
  baselineMarketplaceVolumeSats: number;
  baselineBrowserFlowSats: number;
  baselineTokenFlowSats: number;
  mailEdgeDensity: number;
  mailSatsPerDelivery: number;
  marketplaceAverageSaleSats: number;
  browserAveragePageSats: number;
  tokenAverageMintSats: number;
  satsPerFile: number;
  canonicalFee: number;
  blockspaceVbytesPerYear: number;
  idVbytesPerWrite: number;
  mailVbytesPerWrite: number;
  driveVbytesPerWrite: number;
  marketplaceVbytesPerSale: number;
  browserVbytesPerPage: number;
  tokenVbytesPerWrite: number;
  mailMessagesPerPairPerYear: number;
  driveFilesPerIdPerYear: number;
  marketplaceSalesPerIdPerYear: number;
  browserPagesPerIdPerYear: number;
  tokenMintsPerIdPerYear: number;
  valueMultiple: number;
  elasticities: {
    id: number;
    mail: number;
    drive: number;
    marketplace: number;
    browser: number;
    token: number;
    boost: number;
  };
  horizons: Array<{
    label: string;
    years: number;
    adoption: number;
  }>;
  baselineBoostFlowSats: number;
  boostOriginalPostsPerIdPerYear: number;
  boostOriginalMetadataVbytes: number;
  boostPaidActionsPerIdPerYear: number;
  boostRegistryFeeSats: number;
  boostVbytesPerPaidAction: number;
  boostSalesPerIdPerYear: number;
  boostAverageSaleSats: number;
  boostMarketWritesPerSale: number;
  boostVbytesPerSale: number;
};
export type GrowthModelInputs = {
  bitnodesReachableNodes: number;
  agentShare: number;
  nodeCagr: number;
  currentBtcUsd: number;
  historicalBtcUsd: number;
  btcBenchmarkYears: number;
  currentPowids: number;
  idDensitySatsPerN2: number;
  baselineMailFlowSats: number;
  baselineFileFlowSats: number;
  baselineMarketplaceVolumeSats: number;
  baselineBrowserFlowSats: number;
  baselineTokenFlowSats: number;
  mailEdgeDensity: number;
  mailSatsPerDelivery: number;
  marketplaceAverageSaleSats: number;
  browserAveragePageSats: number;
  tokenAverageMintSats: number;
  satsPerFile: number;
  canonicalFee: number;
  blockspaceVbytesPerYear: number;
  idVbytesPerWrite: number;
  mailVbytesPerWrite: number;
  driveVbytesPerWrite: number;
  marketplaceVbytesPerSale: number;
  browserVbytesPerPage: number;
  tokenVbytesPerWrite: number;
  mailMessagesPerPairPerYear: number;
  driveFilesPerIdPerYear: number;
  marketplaceSalesPerIdPerYear: number;
  browserPagesPerIdPerYear: number;
  tokenMintsPerIdPerYear: number;
  valueMultiple: number;
  elasticities: {
    id: number;
    mail: number;
    drive: number;
    marketplace: number;
    browser: number;
    token: number;
    boost: number;
    wallet: number;
    infinity: number;
    inception: number;
    computerEvent: number;
  };
  horizons: Array<{
    label: string;
    years: number;
    adoption: number;
  }>;
  baselineBoostFlowSats: number;
  boostOriginalPostsPerIdPerYear: number;
  boostOriginalMetadataVbytes: number;
  boostPaidActionsPerIdPerYear: number;
  boostRegistryFeeSats: number;
  boostVbytesPerPaidAction: number;
  boostSalesPerIdPerYear: number;
  boostAverageSaleSats: number;
  boostMarketWritesPerSale: number;
  boostVbytesPerSale: number;
  idRegistrationFeeSats: number;
  idMutationFeeSats: number;
  idMutationsPerIdPerYear: number;
  idMutationVbytesPerWrite: number;
  creditCreatesPerIdPerYear: number;
  creditCreateFeeSats: number;
  creditCreateVbytesPerWrite: number;
  walletGenericTransfersPerIdPerYear: number;
  walletWorkTransfersPerIdPerYear: number;
  walletTransferFeeSats: number;
  walletVbytesPerTransfer: number;
  infinityActionsPerIdPerYear: number;
  infinityAverageBondSats: number;
  infinityVbytesPerAction: number;
  inceptionActionsPerIdPerYear: number;
  inceptionAverageBondSats: number;
  inceptionVbytesPerAction: number;
  workMaxSupply: number;
  marketplaceSaleWrites: number;
  marketplaceCancellationWrites: number;
  marketplaceRegistryFeeSats: number;
  marketplaceVbytesPerWrite: number;
  marketplaceAssets: {
    ids: {
      name: string;
      salesPerIdPerYear: number;
      cancelledListingsPerIdPerYear: number;
      averageSaleSats: number;
    };
    credits: {
      name: string;
      salesPerIdPerYear: number;
      cancelledListingsPerIdPerYear: number;
      averageSaleSats: number;
    };
    work: {
      name: string;
      salesPerIdPerYear: number;
      cancelledListingsPerIdPerYear: number;
      averageSaleSats: number;
    };
    powb: {
      name: string;
      salesPerIdPerYear: number;
      cancelledListingsPerIdPerYear: number;
      averageSaleSats: number;
    };
    incb: {
      name: string;
      salesPerIdPerYear: number;
      cancelledListingsPerIdPerYear: number;
      averageSaleSats: number;
    };
  };
};
export type BoostGrowthForecastRow = {
  label: string;
  years: number;
  adoption: number;
  blockspaceUsageRatio: number;
  rawBlockspaceVbytes: number;
  executedBlockspaceVbytes: number;
  boostSats: number;
  boostWrites: number;
  boostOriginalPosts: number;
  boostPaidActions: number;
  boostSales: number;
  boostVbytes: number;
  rawBoostOriginalPosts: number;
  rawBoostPaidActions: number;
  rawBoostSales: number;
  rawBoostVbytes: number;
  rawBoostSats: number;
  browserSats: number;
  browserWrites: number;
  btcUsdBase: number;
  driveSats: number;
  driveWrites: number;
  idSats: number;
  idWrites: number;
  mailSats: number;
  mailWrites: number;
  marketplaceSats: number;
  marketplaceWrites: number;
  powids: number;
  tokenSats: number;
  tokenWrites: number;
  totalSats: number;
  totalUsdBase: number;
  totalWrites: number;
};
export type AllProductsGrowthForecastRow = BoostGrowthForecastRow & {
  tokenCreateWrites: number;
  tokenMintWrites: number;
  walletSats: number;
  walletWrites: number;
  walletGenericTransferWrites: number;
  walletWorkTransferWrites: number;
  infinitySats: number;
  infinityWrites: number;
  inceptionSats: number;
  inceptionWrites: number;
  computerEventSats: number;
  computerEventWrites: number;
  computerEventActions: number;
  idRegistrationFlowSats: number;
  idMutationFlowSats: number;
  marketplaceByAsset: {
    ids: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    credits: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    work: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    powb: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    incb: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
  };
  workMovementWrites: number;
  workFloorSats: number;
};
export type GrowthForecastRow = BoostGrowthForecastRow & Partial<{
  tokenCreateWrites: number;
  tokenMintWrites: number;
  walletSats: number;
  walletWrites: number;
  walletGenericTransferWrites: number;
  walletWorkTransferWrites: number;
  infinitySats: number;
  infinityWrites: number;
  inceptionSats: number;
  inceptionWrites: number;
  computerEventSats: number;
  computerEventWrites: number;
  computerEventActions: number;
  idRegistrationFlowSats: number;
  idMutationFlowSats: number;
  marketplaceByAsset: {
    ids: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    credits: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    work: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    powb: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
    incb: {
      sales: number;
      cancelledListings: number;
      listings: number;
      seals: number;
      delistings: number;
      writes: number;
      saleVolumeSats: number;
      registryFeeSats: number;
      valueSats: number;
      vbytes: number;
    };
  };
  workMovementWrites: number;
  workFloorSats: number;
}>;
export const GROWTH_MODEL_START_DATE: string;
export const GROWTH_MODEL_GENERATED_ON: string;
export const GROWTH_MODEL_VERSION: string;
export const GROWTH_MODEL_CALIBRATION: string;
export const LEGACY_GROWTH_MODEL_GENERATED_ON: string;
export const BOOST_GROWTH_MODEL_GENERATED_ON: string;
export const BOOST_GROWTH_MODEL_VERSION: string;
export const BOOST_GROWTH_MODEL_CALIBRATION: string;
export const GROWTH_MODEL_INPUTS: GrowthModelInputs;
export const BOOST_GROWTH_MODEL_INPUTS: BoostGrowthModelInputs;
export const LEGACY_GROWTH_MODEL_INPUTS: {
  bitnodesReachableNodes: number;
  agentShare: number;
  nodeCagr: number;
  currentBtcUsd: number;
  historicalBtcUsd: number;
  btcBenchmarkYears: number;
  currentPowids: number;
  idDensitySatsPerN2: number;
  baselineMailFlowSats: number;
  baselineFileFlowSats: number;
  baselineMarketplaceVolumeSats: number;
  baselineBrowserFlowSats: number;
  baselineTokenFlowSats: number;
  mailEdgeDensity: number;
  mailSatsPerDelivery: number;
  marketplaceAverageSaleSats: number;
  browserAveragePageSats: number;
  tokenAverageMintSats: number;
  satsPerFile: number;
  canonicalFee: number;
  blockspaceVbytesPerYear: number;
  idVbytesPerWrite: number;
  mailVbytesPerWrite: number;
  driveVbytesPerWrite: number;
  marketplaceVbytesPerSale: number;
  browserVbytesPerPage: number;
  tokenVbytesPerWrite: number;
  mailMessagesPerPairPerYear: number;
  driveFilesPerIdPerYear: number;
  marketplaceSalesPerIdPerYear: number;
  browserPagesPerIdPerYear: number;
  tokenMintsPerIdPerYear: number;
  valueMultiple: number;
  elasticities: {
    id: number;
    mail: number;
    drive: number;
    marketplace: number;
    browser: number;
    token: number;
  };
  horizons: Array<{
    label: string;
    years: number;
    adoption: number;
  }>;
};
export const GROWTH_MODEL_ROWS: AllProductsGrowthForecastRow[];
export const GROWTH_MODEL_CHART_ROWS: AllProductsGrowthForecastRow[];
export const BOOST_GROWTH_MODEL_ROWS: GrowthForecastRow[];
export const BOOST_GROWTH_MODEL_CHART_ROWS: GrowthForecastRow[];
export const LEGACY_GROWTH_MODEL_ROWS: GrowthForecastRow[];
export const LEGACY_GROWTH_MODEL_CHART_ROWS: GrowthForecastRow[];
export const GROWTH_ASSUMPTIONS: Array<{ product: string; usage: string; value: string; elasticity: string; blockspace: string; attribution: string }>;
export const GROWTH_PRODUCT_COVERAGE: Array<{ product: string; name: string; role: string; owner: string; modeledLane: string; activity: string; assumption: string; source: string }>;
export const GROWTH_MODEL_LIMITATIONS: string[];
export const GROWTH_VALUE_LANES: Array<{ key: "idSats" | "mailSats" | "driveSats" | "browserSats" | "marketplaceSats" | "tokenSats" | "boostSats" | "infinitySats" | "inceptionSats" | "walletSats" | "computerEventSats"; name: string }>;
export function growthFeeMultiplier(feeRate: number, elasticity: number): number;
export function growthBtcUsdAtYears(years: number): number;
export function growthSatsToUsdAtYears(sats: number, years: number): number;
export function boostGrowthModelRow(horizon: GrowthForecastHorizon, inputs?: BoostGrowthModelInputs): BoostGrowthForecastRow;
export function boostGrowthModelStartRow(): BoostGrowthForecastRow;
export function growthModelRow(horizon: GrowthForecastHorizon, inputs?: GrowthModelInputs): AllProductsGrowthForecastRow;
export function growthModelStartRow(): AllProductsGrowthForecastRow;
