import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';import * as A from './pow-audit30-private-sixteen-commit-inverse-adapter-v1.mjs';
const source=fs.readFileSync('/tmp/pow-audit30-private-sixteen-commit-inverse-adapter-v1.mjs','utf8');
function admission(){return {environment:'privateclone',operation:'apply',originalPlanSHA256:A.PLAN_SHA,manifestSHA256:A.MANIFEST_SHA,engineSHA256:A.LIBRARY_SHA,productionApplyApproved:false,approvalReceiptSHA256:null,priorAcknowledgedApplyReceiptSHA256:null,expectedDatabaseIdentity:{dataDirectory:A.JOB+'/cluster',socket:A.JOB+'/socket',port:'55432',database:'proof_indexer',user:'postgres'}};}
test('native proof is only existing014100 clone, no live/inverse entrypoint',()=>{const a=admission();assert.equal(A.validatePrivateAdmission(a),a);assert.equal(A.JOB,'/data/proofofwork-audit30-inspect-20261003T014100Z');assert.equal(A.EVIDENCE_DIRECTORY,A.JOB+'/exact-sixteen-write-proof-v1');});
for(const [field,value]of [['environment','production'],['operation','inverse'],['productionApplyApproved',true],['approvalReceiptSHA256','a'.repeat(64)],['priorAcknowledgedApplyReceiptSHA256','b'.repeat(64)],['engineSHA256','c'.repeat(64)],['originalPlanSHA256','d'.repeat(64)]])test('private admission refuses '+field,()=>{const a=admission();a[field]=value;assert.throws(()=>A.validatePrivateAdmission(a),/PRIVATE014100_ADMISSION/);});
test('other cluster/production socket cannot be selected',()=>{for(const [field,value]of [['dataDirectory','/var/lib/postgresql/16/main'],['socket','/var/run/postgresql'],['port','5432'],['user','proof_indexer'],['database','postgres']]){const a=admission();a.expectedDatabaseIdentity[field]=value;assert.throws(()=>A.validatePrivateAdmission(a),/PRIVATE014100_ADMISSION/);}});
test('invalid argv fails before any path, import or database access',async()=>{await assert.rejects(()=>A.nativeMain([]),/FIXED_PRIVATE_ARGV/);await assert.rejects(()=>A.nativeMain(['a'.repeat(64),'b'.repeat(64),'/other']),/FIXED_PRIVATE_ARGV/);});
test('actual local CLI refusal is closed and has no live authority',()=>{const r=spawnSync(process.execPath,['/tmp/pow-audit30-private-sixteen-commit-inverse-adapter-v1.mjs'],{encoding:'utf8',timeout:5000});assert.ifError(r.error);assert.equal(r.status,1);assert.equal(r.stdout,'');const v=JSON.parse(r.stderr);assert.equal(v.code,'FIXED_PRIVATE_ARGV');assert.equal(v.productionMutation,false);assert.equal(v.liveApproval,false);assert.equal(v.automaticRetry,false);});
test('imports execute only after all raw source/plan/dependency pins',()=>{assert.ok(source.indexOf('const bytes=new Map')<source.indexOf('await import('));for(const p of [A.PLAN_SHA,A.MANIFEST_SHA,A.EA56_SHA,A.ORIGINAL_ENGINE_SHA,A.LIBRARY_SHA])assert.ok(source.includes(p));assert.ok(source.indexOf('EVIDENCE_PREFIX_COLLISION')<source.indexOf('const efd=fs.openSync'));assert.ok(source.includes('fs.fsyncSync(efd)'));});
test('database connection is fixed privateUnix and environment cannot redirect it',()=>{assert.ok(source.includes("host:JOB+'/socket',port:55432,user:'postgres',database:'proof_indexer'"));assert.ok(source.includes('PRIVATE_CLEAN_ENVIRONMENT'));assert.ok(source.includes("k.startsWith('PG')"));assert.ok(source.includes("['NODE_OPTIONS','DATABASE_URL','PROOF_INDEX_DATABASE_URL','POW_INDEX_DATABASE_URL']"));assert.equal(source.includes('postgresql://'),false);});
test('only separately acknowledged apply supplies inverse receipt, no failure auto inverse',()=>{assert.ok(source.indexOf('const apply=await W.writeExactSixteen')<source.indexOf('const inverse=await W.writeExactSixteen'));assert.ok(source.includes('priorAcknowledgedApplyReceiptBytes:applyBytes'));assert.ok(source.includes("priorAcknowledgedApplyReceiptSHA256:hash(applyBytes)"));assert.ok(source.includes('source7Accessed:false'));assert.equal(source.includes('source7Changed:false'),false);});
