import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as E from './pow-audit30-mail-body-repair-rehearsal-v2.mjs';
import {pathToFileURL} from 'node:url';
const originalEngineBytes=fs.readFileSync('/tmp/pow-audit30-mail-body-repair-rehearsal.mjs');
const seed=JSON.parse(fs.readFileSync('/tmp/pow-audit30-mail-body-repair-synthetic-plan.json'));
const source=fs.readFileSync('/tmp/pow-audit30-mail-body-exact-sixteen-write-candidate-v1.mjs','utf8'),engineSHA=E.hash(source);
const job='/data/proofofwork-audit30-inspect-20261003T014100Z',copy=x=>structuredClone(x);
function closure(){
 const c={schema:'pow-audit30-readiness-public-closure-v2',functions:Object.keys(E.FUNCTION_SOURCE_SHA).sort().map(name=>({name,owner:name.startsWith('reject_')?'proof_indexer':'proof_indexer_readiness_owner',language:'plpgsql',securityDefiner:!name.startsWith('reject_'),config:name.startsWith('reject_')?null:['search_path=pg_catalog, pg_temp'],kind:'f',argumentCount:0,returnsSet:false,returnTypeOid:2279,volatility:'v',parallel:'u',strict:false,leakProof:false,supportOid:0,canonicalSourceEquality:true,sourceSha256:E.FUNCTION_SOURCE_SHA[name],sourceBytes:E.FUNCTION_SOURCE_BYTES[name],definitionSha256:E.hash('definition-'+name),acl:(name.startsWith('reject_')?['PUBLIC','proof_indexer']:['proof_indexer','proof_indexer_readiness_owner']).map(grantee=>({grantee,grantor:name.startsWith('reject_')?'proof_indexer':'proof_indexer_readiness_owner',privilege:'EXECUTE',grantable:false}))})),triggers:[],relations:[],ownerRole:{name:'proof_indexer_readiness_owner',login:false,superuser:false,createRole:false,createDb:false,replication:false,bypassRls:false,inherit:true,connectionLimit:-1,noExpiry:true,noConfiguration:true,schemaUsage:true,memberships:0}};
 const trigger=(relation,name,fn,type,def=false)=>({relation,name,function:fn,functionSchema:'proof_indexer',enabled:'A',type,internal:false,deferrable:def,initiallyDeferred:def,hasConstraint:def,argumentCount:0,argumentBytes:0,noCondition:true,oldTransitionTable:null,newTransitionTable:null,noParent:true,definitionSha256:E.hash('definition-'+name)});
 c.triggers=E.READINESS_TABLES.map(relation=>trigger(relation,'readiness_epoch_'+relation,'enqueue_livenet_readiness_epoch',60));c.triggers.push(trigger('meta','readiness_epoch_meta','enqueue_livenet_readiness_epoch_for_meta',29),trigger('meta','readiness_epoch_meta_truncate','enqueue_livenet_readiness_epoch',32),trigger('readiness_epoch_queue','readiness_epoch_commit','commit_livenet_readiness_epoch',5,true));for(const [name,fn] of [['work_amo_v6_migration_marker_immutable','reject_work_amo_v6_migration_marker_mutation'],['work_precision_v2_marker_immutable','reject_work_precision_v2_marker_mutation']])c.triggers.push({...trigger('meta',name,fn,27),enabled:'O',definitionSha256:E.MARKER_TRIGGER_SHA[name]});c.triggers.sort((a,b)=>a.relation.localeCompare(b.relation)||a.name.localeCompare(b.name));
 for(const name of ['mail_items','meta','readiness_epoch_queue','readiness_epoch_shards']){const journal=name.startsWith('readiness_epoch_'),queue=name.endsWith('queue');const r={name,owner:journal?'proof_indexer_readiness_owner':'proof_indexer',kind:'r',persistence:'p',rls:false,forceRls:false,accessMethod:'heap',ruleCount:0,inheritanceCount:0,columns:[],constraints:[],indexes:[],acl:[]};if(journal){const cols=queue?[['transaction_id',5069,'xid8'],['network',25,'text'],['shard',21,'smallint'],['enqueued_at',1184,'timestamp with time zone']]:[['network',25,'text'],['shard',21,'smallint'],['epoch',20,'bigint'],['updated_at',1184,'timestamp with time zone']];r.columns=cols.map(([name,typeOid,type],i)=>({ordinal:i+1,name,typeOid,type,notNull:true,dropped:false,identity:'',generated:'',defaultSha256:i===3?E.hash('clock_timestamp()'):null,acl:[]}));const co=(name,type,d,def=false)=>({name,type,validated:true,deferrable:def,initiallyDeferred:def,definitionSha256:E.hash(d)});r.constraints=queue?[co('readiness_epoch_commit','t','TRIGGER DEFERRABLE INITIALLY DEFERRED',true),co('readiness_epoch_queue_pkey','p','PRIMARY KEY (transaction_id)'),co('readiness_epoch_queue_shard_check','c','CHECK (((shard >= 0) AND (shard < 64)))')]:[co('readiness_epoch_shards_epoch_check','c','CHECK ((epoch >= 1))'),co('readiness_epoch_shards_pkey','p','PRIMARY KEY (network, shard)'),co('readiness_epoch_shards_shard_check','c','CHECK (((shard >= 0) AND (shard < 64)))')];r.indexes=[{name:name+'_pkey',valid:true,ready:true,live:true,unique:true,primary:true,immediate:true,exclusion:false,nullsNotDistinct:false,definitionSha256:E.hash('CREATE UNIQUE INDEX '+name+'_pkey ON proof_indexer.'+name+' USING btree ('+(queue?'transaction_id':'network, shard')+')')}];r.acl=[{grantee:'proof_indexer',grantor:'proof_indexer_readiness_owner',privilege:'SELECT',grantable:false},...['DELETE','INSERT','REFERENCES','SELECT','TRIGGER','TRUNCATE','UPDATE'].map(privilege=>({grantee:'proof_indexer_readiness_owner',grantor:'proof_indexer_readiness_owner',privilege,grantable:false}))];}c.relations.push(r);}
 return c;
}
class Client{
 constructor(p){this.p=p;this.current=new Map(p.sourceRows.map(r=>{const x=JSON.parse(Buffer.from(r.recordBase64,'base64'));return[x.txid,x.mail.body_text]}));this.original=new Map(this.current);this.calls=[];this.selected=0;this.beforeBegin=false;this.locked=false;this.extra='same';this.catalog=closure();this.xid='9007199254741009';this.queue=[];this.shards=Array.from({length:64},(_,shard)=>({network:'livenet',shard,epoch:'9007199254740993',updatedAt:'2026-10-02 00:00:00+00'}));this.originalShards=copy(this.shards);this.meta='same';this.originalMeta='same';}
 fingerprint(){return {count:this.current.size+1,logical_bytes:'200',sha256:E.hash(E.encoded([...this.current])+this.extra)};}
 async query(q){this.calls.push(q);if(this.onQuery)await this.onQuery(q);const {text,values}=q;
 if(text===E.SQL.begin){this.beforeBegin=true;return {rows:[]};}
 if(text===E.SQL.locks){this.locked=true;return {rows:[]};}
 if(text===E.SQL.settings)return {rows:[]};
 assert.equal(this.locked,true,'all snapshot/catalog reads follow fixed source locks');
 if(text===E.SQL.identity)return {rows:[{value:{dataDirectory:job+'/cluster',socket:job+'/socket',listenAddresses:'',port:'55432',readOnly:'on',checksums:'on',user:'postgres',database:'proof_indexer',serverAddress:null,...this.identityOverride}}]};
 if(text===E.SQL.closure){const c=copy(this.catalog);if(this.triggers)c.triggers.push({...c.triggers[0],name:'unknown'});return {rows:[{value:{closure:c,closureSha256:E.hash(E.pgJsonbText(c)),identity:{maxPreparedTransactions:this.maxPrepared??'0'}}}]};}
 if(text===E.SQL.transactionId)return {rows:[{xid:this.xid}]};
 if(text===E.SQL.journalState)return {rows:[{value:{queue:copy(this.queue),shards:copy(this.shards)}}]};
 if(text===E.SQL.journalFingerprints){const fp=x=>({count:x.length,logical_bytes:String(x.length*200),sha256:E.hash(E.encoded(x))});return {rows:[{value:{queue:fp(this.queue),shards:fp(this.shards),meta:fp([this.meta])}}]};}
 if(text===E.SQL.namedConstraint){this.constraintCalls=(this.constraintCalls??0)+1;const r=this.shards.find(x=>x.network==='livenet'&&x.shard===Number(BigInt(this.xid)%64n));r.epoch=(BigInt(r.epoch)+1n).toString();r.updatedAt='2026-10-03 00:00:00+00';this.queue=[];if(this.onFlush)this.onFlush();return {rows:[]};}
 if(text===E.SQL.fullFingerprint)return {rows:[this.fingerprint()]};
 if(text===E.SQL.baseline)return {rows:[]};
 if(text===E.SQL.source){const src=JSON.parse(values[0]);if(!this.current.has(values[1]))return {rows:[]};return {rows:[{mail_match:this.current.get(values[1])===src.mail.body_text,transaction_match:!this.sourceDrift,block_match:true,events_match:true,carriers_match:true}]};}
 if(text===E.SQL.update||text===E.SQL.inverseUpdate){const [to,id,from,raw]=values;assert.equal(typeof raw,'string');if(this.zeroUpdate)return {rowCount:0,rows:[]};assert.equal(this.current.get(id),from);this.current.set(id,to);if(!this.queue.length)this.queue=[{transactionId:this.xid,network:'livenet',shard:Number(BigInt(this.xid)%64n),enqueuedAt:'2026-10-03 00:00:00+00'}];return {rowCount:1,rows:[{txid:id}]};}
 if(text===E.SQL.invariance)return {rows:[{same_count:true,all_nonbody_same:!this.nonbodyChange,nontarget_same:!this.nontargetChange,other_network_same:true}]};
 if(text===E.SQL.exactTargets)return {rows:values[0].map(txid=>({txid,body_text:this.current.get(txid)}))};
 if(text===E.SQL.rollback){if(this.failRollback)throw new Error('private body database details');this.current=new Map(this.original);this.queue=[];this.shards=copy(this.originalShards);this.meta=this.originalMeta;return {rows:[]};}
 throw new Error('unexpected SQL '+text);
 }
}
// Synthetic algorithm fixtures rebind ONLY the two immutable plan-authority
// constants in a data-URL copy. The production candidate remains byte-unchanged,
// its real 4ac3/8d5 pins and LIVE_APPROVAL_PIN=null are tested separately below.
function plan16(wide=false){
 const p=copy(seed);p.sourceRows=[];p.targets=[];p.manifest.targets=[];p.manifest.populationRows=16;p.manifest.targetCount=16;
 for(let i=0;i<16;i++){const s=seed.sourceRows[i%2],old=s.txid,id=(i+1).toString(16).padStart(64,'0');let raw=Buffer.from(s.recordBase64,'base64').toString('utf8').replaceAll(old,id);if(wide&&i===0)raw=raw.slice(0,-1)+',"wide":9007199254740993.1234567890123456789}';const t=JSON.parse(JSON.stringify(seed.targets[i%2]).replaceAll(old,id)),sha=E.hash(raw);t.rawSourceRecordSHA256=sha;p.sourceRows.push({txid:id,recordBase64:Buffer.from(raw).toString('base64'),recordSHA256:sha});p.targets.push(t);p.manifest.targets.push({network:t.network,txid:id,sourceRecordSHA256:sha,proof:t.publicProof});}
 const snapshot=JSON.parse(Buffer.from(p.snapshotRawBase64,'base64'));snapshot.mailRows=16;p.snapshotRawBase64=Buffer.from(E.encoded(snapshot)).toString('base64');p.manifestSHA256=E.hash(E.encoded(p.manifest));return p;
}
async function fixtureModule(p){let s=source;for(const [from,to] of [["ORIGINAL_PLAN_SHA='4ac3a8d9b4b79befd36abc590731b1bc8f2e6c83919d5f6427c34c58a6ddba00'",`ORIGINAL_PLAN_SHA='${E.hash(Buffer.from(E.encoded(p)))}'`],["ORIGINAL_MANIFEST_SHA='8d5d347aea2d398d75e69631f90b3efdd1c3254cfdbf3864015199b078699c50'",`ORIGINAL_MANIFEST_SHA='${p.manifestSHA256}'`],["from './pow-audit30-mail-body-repair-rehearsal-v2.mjs'",`from '${pathToFileURL('/tmp/pow-audit30-mail-body-repair-rehearsal-v2.mjs')}'`]]){assert.equal(s.split(from).length,2);s=s.replace(from,to);}return import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));}
class WriteClient extends Client{
 async query(q){if(q.text===E.SQL.begin){this.original=new Map(this.current);this.originalShards=copy(this.shards);this.originalMeta=this.meta;this.xid=(BigInt(this.xid)+1n).toString();}
  if(q.text===E.SQL.rollback&&!this.locked){this.calls.push(q);this.current=new Map(this.original);this.queue=[];this.shards=copy(this.originalShards);this.meta=this.originalMeta;return {rows:[]};}
  if(q.text.startsWith('SELECT to_jsonb(m)=jsonb_set(')){this.calls.push(q);if(this.onQuery)await this.onQuery(q);assert.equal(q.values.length,3);assert.match(q.values[0],/"phase"\s*:\s*"row"/u);return {rows:[{mail_match:this.current.get(q.values[1])===q.values[2],transaction_match:!this.sourceDrift,block_match:true,events_match:true,carriers_match:true}]};}
  if(q.text==='COMMIT'){this.calls.push(q);this.commitCalls=(this.commitCalls??0)+1;if(this.onCommit)await this.onCommit();if(this.commitFails)throw Error('private connection lost');this.committedBodies=new Map(this.current);return {rows:[]};}
  return super.query(q);
 }
}
function admission(W,p,c,operation='apply',prior=null){return {schema:'pow-audit30-exact-sixteen-write-admission-v1',environment:'privateclone',operation,originalPlanSHA256:W.ORIGINAL_PLAN_SHA,manifestSHA256:p.manifestSHA256,engineSHA256:engineSHA,readinessClosureSHA256:E.hash(E.pgJsonbText(c.catalog)),targetTxidSetSHA256:E.hash(E.encoded(p.targets.map(t=>t.txid))),expectedDatabaseIdentity:{dataDirectory:job+'/cluster',socket:job+'/socket',listenAddresses:'',port:'55432',readOnly:'on',checksums:'on',user:'postgres',database:'proof_indexer',serverAddress:null},approvalReceiptSHA256:null,productionApplyApproved:false,priorAcknowledgedApplyReceiptSHA256:prior?E.hash(prior):null};}
async function run(p=plan16(),c=new WriteClient(p),extra={}){const W=await fixtureModule(p),receipts=[],fences=[],a=admission(W,p,c,extra.operation??'apply',extra.priorAcknowledgedApplyReceiptBytes??null);const options={originalPlanBytes:Buffer.from(E.encoded(p)),originalPlanSHA256:W.ORIGINAL_PLAN_SHA,originalEngineBytes,engineSHA256:engineSHA,admission:a,durable:async(n,r)=>receipts.push({n,r}),fence:async n=>fences.push(n),...extra};try{return {result:await W.writeExactSixteen(c,p,options),c,receipts,fences,W,a};}catch(error){return {error,c,receipts,fences,W,a};}}
test('original candidate keeps exact real authority and cannot approve production',async()=>{const W=await import('./pow-audit30-mail-body-exact-sixteen-write-candidate-v1.mjs');assert.equal(W.ORIGINAL_PLAN_SHA,'4ac3a8d9b4b79befd36abc590731b1bc8f2e6c83919d5f6427c34c58a6ddba00');assert.equal(W.ORIGINAL_MANIFEST_SHA,'8d5d347aea2d398d75e69631f90b3efdd1c3254cfdbf3864015199b078699c50');assert.equal(W.LIVE_APPROVAL_PIN,null);assert.equal(source.includes('nativeMain'),false);const c=new WriteClient(plan16());await assert.rejects(()=>W.writeExactSixteen(c,plan16(),{originalPlanBytes:Buffer.from(E.encoded(plan16()))}),/ORIGINAL_PLAN_BYTES_PIN/);assert.equal(c.calls.length,0);});
test('all sixteen synthetic exact preimages pass the unchanged original producer verifier',()=>{assert.equal(E.validateOriginalProducerAuthority(plan16(),originalEngineBytes).size,16);});
test('acknowledged apply commits exactly16 bodies, preserves nonbody/nontargets and invalidates one shard',async()=>{const r=await run();assert.ifError(r.error);assert.equal(r.result.targetCount,16);assert.equal(r.result.commitAcknowledged,true);assert.equal(r.c.commitCalls,1);assert.equal(r.c.calls.filter(q=>q.text===E.SQL.update).length,16);assert.equal(r.c.calls.some(q=>q.text==='ROLLBACK'),false);assert.equal(r.c.constraintCalls,1);assert.deepEqual(r.c.current,r.c.committedBodies);assert.deepEqual(r.c.queue,[]);assert.equal(r.result.operationalEpochAfter,'9007199254740994');assert.equal(r.result.productionMutation,false);assert.deepEqual(r.receipts.map(x=>x.n),['intent','selected-preimages','commit-intent','completed']);assert.deepEqual(r.fences,['before-transaction','before-first-update','before-commit','after-acknowledged-commit']);});
test('separately acknowledged inverse restores original NULL/text under native JSONB guards and second epoch',async()=>{const p=plan16(true),c=new WriteClient(p),forward=await run(p,c);assert.ifError(forward.error);const prior=Buffer.from(E.encoded(forward.result)),inverse=await run(p,c,{operation:'inverse',priorAcknowledgedApplyReceiptBytes:prior});assert.ifError(inverse.error);assert.equal(c.commitCalls,2);assert.equal(c.constraintCalls,2);assert.deepEqual([...c.current],p.targets.map(t=>[t.txid,t.oldBody]));assert.equal(c.current.get(p.targets[1].txid),null);assert.equal(inverse.result.operationalEpochRewind,false);assert.equal(inverse.result.operationalEpochBefore,'9007199254740993');const inv=c.calls.find(q=>q.text.startsWith('SELECT to_jsonb(m)=jsonb_set('));assert.match(inv.values[0],/9007199254740993\.1234567890123456789/);const u=c.calls.find(q=>q.text===E.SQL.inverseUpdate);assert.match(u.values[3],/9007199254740993\.1234567890123456789/);assert.equal(c.calls.some(q=>/SET epoch\s*=|DISABLE TRIGGER|session_replication_role/.test(q.text)),false);});
test('durable preimage refusal sends no update and rolls back once',async()=>{const r=await run(undefined,undefined,{durable:async n=>{if(n==='selected-preimages')throw Error('private data');}});assert.ok(r.error);assert.equal(r.c.calls.some(q=>q.text===E.SQL.update),false);assert.equal(r.c.calls.filter(q=>q.text==='ROLLBACK').length,1);});
test('durable commit-intent refusal rolls all16 updates back and sends no COMMIT',async()=>{const r=await run(undefined,undefined,{durable:async n=>{if(n==='commit-intent')throw Error('private data');}});assert.ok(r.error);assert.equal(r.c.commitCalls,undefined);assert.deepEqual(r.c.current,r.c.original);});
test('lost COMMIT reply remains unknown and cannot claim rollback or automatic retry',async()=>{const p=plan16(),c=new WriteClient(p);c.commitFails=true;const r=await run(p,c);assert.ok(r.error);assert.equal(c.commitCalls,1);assert.equal(c.calls.some(q=>q.text==='ROLLBACK'),false);const f=r.receipts.at(-1).r;assert.equal(f.commitOutcome,'unknown');assert.equal(f.rollbackAcknowledged,false);assert.equal(f.unknownCommitRequiresExplicitReconciliation,true);assert.equal(f.automaticRetry,false);assert.equal(JSON.stringify(f).includes('private connection'),false);});
test('postacknowledgement drift is recorded committed, never rolled back or retried',async()=>{const p=plan16(),c=new WriteClient(p);c.onCommit=()=>c.current.set(p.targets[0].txid,'changed later');const r=await run(p,c);assert.match(r.error.message,/ACKNOWLEDGED_POSTIMAGE_CHANGED/);assert.equal(r.receipts.at(-1).r.commitOutcome,'acknowledged');assert.equal(c.calls.some(q=>q.text==='ROLLBACK'),false);});
test('postcommit unrelated worker epoch increments do not turn acknowledged exact proof into corruption',async()=>{const p=plan16(),c=new WriteClient(p);c.onCommit=()=>{const row=c.shards[0];row.epoch=(BigInt(row.epoch)+20n).toString();c.extra='normal unrelated ingestion';};const r=await run(p,c);assert.ifError(r.error);assert.equal(r.result.operationalEpochAfter,'9007199254740994');assert.equal(r.result.commitAcknowledged,true);});
for(const flag of ['sourceDrift','nonbodyChange','nontargetChange','zeroUpdate','triggers'])test('refuses meaningful transaction drift '+flag,async()=>{const p=plan16(),c=new WriteClient(p);c[flag]=true;const r=await run(p,c);assert.ok(r.error);assert.equal(c.commitCalls,undefined);assert.deepEqual(c.current,c.original);assert.equal(r.receipts.at(-1).r.rollbackAcknowledged,true);});
test('one missing target refuses full16 scope rather than clone-subset qualification',async()=>{const p=plan16(),c=new WriteClient(p);c.current.delete(p.targets[0].txid);const r=await run(p,c);assert.match(r.error.message,/TARGET_FULL_PREIMAGE_DRIFT/);assert.equal(c.calls.some(q=>q.text===E.SQL.update),false);});
test('abort after first update restores all targets and sends no COMMIT',async()=>{const p=plan16(),c=new WriteClient(p),ctrl=new AbortController();c.onQuery=q=>{if(q.text===E.SQL.update)ctrl.abort();};const r=await run(p,c,{signal:ctrl.signal});assert.match(r.error.message,/WRITE_INTERRUPTED/);assert.deepEqual(c.current,c.original);assert.equal(c.commitCalls,undefined);});
test('acknowledged BEGIN followed by abort still performs bounded ROLLBACK',async()=>{const p=plan16(),c=new WriteClient(p),ctrl=new AbortController();c.onQuery=q=>{if(q.text===E.SQL.begin)ctrl.abort();};const r=await run(p,c,{signal:ctrl.signal});assert.match(r.error.message,/WRITE_INTERRUPTED/);assert.equal(c.beforeBegin,true);assert.equal(c.calls.filter(q=>q.text===E.SQL.rollback).length,1);assert.equal(r.receipts.at(-1).r.rollbackAcknowledged,true);assert.equal(c.commitCalls,undefined);});
test('uncertain BEGIN failure attempts ROLLBACK and records not-sent COMMIT',async()=>{const p=plan16(),c=new WriteClient(p);c.onQuery=q=>{if(q.text===E.SQL.begin)throw Error('native database refusal');};const r=await run(p,c);assert.ok(r.error);assert.equal(c.calls.filter(q=>q.text===E.SQL.rollback).length,1);assert.equal(r.receipts.at(-1).r.commitOutcome,'not-sent');assert.equal(r.receipts.at(-1).r.rollbackAcknowledged,true);});
test('source pins and identity refuse before any historical update',async()=>{const p=plan16(),c=new WriteClient(p);c.identityOverride={dataDirectory:'/var/lib/postgresql/16/main'};const r=await run(p,c);assert.match(r.error.message,/DATABASE_IDENTITY_CHANGED/);assert.equal(c.calls.some(q=>q.text===E.SQL.update),false);});
test('empty queue and complete shards are required before updates',async()=>{const p=plan16(),c=new WriteClient(p);c.queue=[{transactionId:'1',network:'livenet',shard:1,enqueuedAt:'old'}];const r=await run(p,c);assert.match(r.error.message,/READINESS_BASELINE_STATE/);assert.equal(c.calls.some(q=>q.text===E.SQL.update),false);});
test('extra readiness shard or meta changes refuse before COMMIT',async()=>{for(const flag of ['shards','meta']){const p=plan16(),c=new WriteClient(p);c.onFlush=()=>{if(flag==='shards')c.shards[(Number(BigInt(c.xid)%64n)+1)%64].epoch='22';else c.meta='unexpected';};const r=await run(p,c);assert.ok(r.error);assert.equal(c.commitCalls,undefined);}});
test('only body UPDATEs and one named constraint are emitted, no insert/delete/epoch rewinds',async()=>{const r=await run();assert.ifError(r.error);for(const q of r.c.calls){assert.ok(q.query_timeout>0&&q.query_timeout<=45000);assert.doesNotMatch(q.text,/SET CONSTRAINTS ALL|DISABLE TRIGGER|session_replication_role|^INSERT |^DELETE |^TRUNCATE /);if(q.text.startsWith('UPDATE'))assert.match(q.text,/^UPDATE proof_indexer\.mail_items AS m SET body_text=\$1/);}
 assert.equal(r.c.calls[0].text,E.SQL.begin);assert.equal(r.c.calls[2].text,E.SQL.locks);assert.match(E.SQL.settings,/statement_timeout='30s'/);assert.match(E.SQL.settings,/lock_timeout='3s'/);assert.equal(r.c.calls.filter(q=>q.text===E.SQL.namedConstraint).length,1);});
test('canonical acknowledged apply receipt is required before inverse SQL',async()=>{const p=plan16(),c=new WriteClient(p),apply=await run(p,c);assert.ifError(apply.error);const mutations=[r=>r.commitAcknowledged=false,r=>r.status='failed',r=>r.operation='inverse',r=>r.environment='production',r=>r.orderedTargetTxids.reverse(),r=>r.engineSHA256='0'.repeat(64),r=>r.originalPlanSHA256='0'.repeat(64),r=>r.queueFlushedBeforeCommit=false,r=>r.operationalEpochAfter=r.operationalEpochBefore];for(const mutate of mutations){const bad=copy(apply.result);mutate(bad);const raw=Buffer.from(E.encoded(bad)),n=new WriteClient(p),r=await run(p,n,{operation:'inverse',priorAcknowledgedApplyReceiptBytes:raw});assert.ok(r.error);assert.equal(n.calls.length,0);}});
test('private mode cannot turn false approval into live authority',async()=>{const p=plan16(),c=new WriteClient(p),W=await fixtureModule(p),a=admission(W,p,c);a.environment='production';a.productionApplyApproved=true;a.approvalReceiptSHA256='a'.repeat(64);const r=await run(p,c,{admission:a});assert.match(r.error.message,/LIVE_NOT_APPROVED/);assert.equal(c.calls.length,0);});
test('acknowledged completion custody failure reports committed, not unknown',async()=>{const r=await run(undefined,undefined,{durable:async(n)=>{if(n==='completed')throw Error('private file failure');}});assert.ok(r.error);assert.equal(r.c.commitCalls,1);assert.equal(r.c.calls.some(q=>q.text==='ROLLBACK'),false);});
test('acknowledged inverse cannot borrow an apply receipt from another private clone',async()=>{const p=plan16(),c=new WriteClient(p),apply=await run(p,c);assert.ifError(apply.error);const r=copy(apply.result);r.expectedDatabaseIdentity={...r.expectedDatabaseIdentity,dataDirectory:'/data/proofofwork-audit30-inspect-20261003T000001Z/cluster',socket:'/data/proofofwork-audit30-inspect-20261003T000001Z/socket'};const target=new WriteClient(p),result=await run(p,target,{operation:'inverse',priorAcknowledgedApplyReceiptBytes:Buffer.from(E.encoded(r))});assert.match(result.error.message,/PRIOR_APPLY_RECEIPT_SCOPE/);assert.equal(target.calls.length,0);});
