import ast,hashlib,json,os,pathlib,shlex,subprocess,sys
MODE=sys.argv[1];assert MODE in ('positive','bond');BUDGET={'positive':450,'bond':330}[MODE]
UNIT='proofofwork-audit30-candidate-full-ids-38ac6e2bff2a-20261003T042000Z-fence-diagnostic-v3.service'
CODE="import datetime,json,subprocess,time\nENV={'PATH':'/usr/bin:/bin','LC_ALL':'C'}\ndef state(u):\n r=subprocess.run(['/usr/bin/systemctl','show',u,'--property=LoadState,ActiveState,SubState,MainPID,InvocationID,Result,RuntimeMaxUSec,ExecMainStartTimestampMonotonic'],env=ENV,capture_output=True,timeout=10)\n assert r.returncode==0 and not r.stderr and len(r.stdout)<65536\n return dict(v.split('=',1)for v in r.stdout.decode().splitlines()if '='in v)\nunits=['bitcoind.service','electrs.service','postgresql@16-main.service','proofofwork-api.service','proofofwork-indexer-worker.service']\nexpected=[('1324302','64e1fa7be2e2442d8c7f5763f60b85fb'),('1324320','72418b1c7ab245e4a37685ed868a1084'),('1537429','e0bf545f0ad944e89fe1005577e61b9c'),('2103747','208f8bcbecc54afbb7166754f12065c2'),('2103760','33b3ee25490749db89e0d55fd29d0afb')]\nobserved={u:state(u)for u in units};audit=state(UNIT);backup=state('proofofwork-postgres-logical-backup.service');shadow=state(SHADOW_UNIT)\nassert all(observed[u]['MainPID']==p and observed[u]['InvocationID']==i and observed[u]['ActiveState']=='active' for u,(p,i)in zip(units,expected))\nassert audit['MainPID']=='0' and audit['ActiveState']in ['inactive','failed']\nassert (audit['LoadState']=='not-found'and audit['InvocationID']=='')or(audit['LoadState']=='loaded'and len(audit['InvocationID'])==32)\nassert backup['ActiveState']=='inactive' and backup['MainPID']=='0' and backup['Result']=='success'\nassert shadow['RuntimeMaxUSec']=='45min' and shadow['ExecMainStartTimestampMonotonic'].isdigit()\nstarted=int(shadow['ExecMainStartTimestampMonotonic'])/1000000;now=time.monotonic();assert 0<started<=now and now-started<=45*60-BUDGET-30\nleaseRemainingSeconds=45*60-(now-started)\nassert shadow['ActiveState']=='active' and shadow['InvocationID']==SHADOW_INVOCATION and shadow['MainPID']==SHADOW_PID\nmetadataBefore=dict(unit=UNIT,audit=audit,shadow=shadow,backup=backup,liveServices=observed,shadowLeaseRemainingSeconds=leaseRemainingSeconds,wholeOuterBudgetSeconds=BUDGET)\nassert state(SHADOW_UNIT)==shadow and {u:state(u)for u in units}==observed and state('proofofwork-postgres-logical-backup.service')==backup\nfinalNow=time.monotonic();finalRemaining=45*60-(finalNow-started);assert 0<started<=finalNow and finalRemaining>=BUDGET+30\nmetadataBefore['shadowLeaseRemainingAtReturnSeconds']=finalRemaining\nprint(json.dumps(dict(schema='pow-audit30-followup-exact-shadow-metadata-v1',atUtc=datetime.datetime.now(datetime.timezone.utc).isoformat(),mode=MODE,admitted=True,metadata=metadataBefore,productionMutation=False,timerChanges=False,additionalAPIRequests=0),sort_keys=True))\n"
ready_raw=pathlib.Path('/tmp/pow-audit30-node-shadow-lease-prepared-38ac-v1.json').read_bytes();assert hashlib.sha256(ready_raw).hexdigest()=='80be65b04cefabc5221e302e7b898ebeb8ac914f5793bbb447d800d821934237';ready=json.loads(ready_raw)['result']
audit_raw=pathlib.Path('/tmp/pow-audit30-candidate-full-id-cli-fence-diagnostic-v3-native-v1.json').read_bytes();assert hashlib.sha256(audit_raw).hexdigest()=='b4d6983561c1cf80eca52fa80d04877d72fdd75fc285f7fa24592d4eb469ff10';a=json.loads(audit_raw);assert a['complete']is True and a['returncode']==0 and a['changedFenceFields']==[]
out=pathlib.Path('/tmp/pow-audit30-'+MODE+'-followup-shadow-admission-v2.json');assert not os.path.lexists(out)
for name in {'positive':['pow-audit30-candidate-positive-work-probe-38ac-v2.json','pow-audit30-candidate-positive-work-probe-38ac-v2.json.stdout','pow-audit30-candidate-positive-work-probe-38ac-v2.json.stderr'],'bond':['pow-audit30-candidate-bond-paging-native-38ac-v2.json']}[MODE]:assert not os.path.lexists(pathlib.Path('/tmp')/name)
code='UNIT='+repr(UNIT)+'\nSHADOW_UNIT='+repr(ready['unit'])+'\nSHADOW_INVOCATION='+repr(ready['invocationID'])+'\nSHADOW_PID='+repr(str(ready['mainPID']))+'\nBUDGET='+repr(BUDGET)+'\nMODE='+repr(MODE)+'\n'+CODE
argv=['ssh','-i','/home/sixer/.ssh/proofofwork_node_ed25519','-o','BatchMode=yes','-o','IdentitiesOnly=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10','powadmin@65.108.122.87',shlex.join(['sudo','-n','/usr/bin/python3','-I','-B','-'])]
r=subprocess.run(argv,input=code.encode(),capture_output=True,timeout=90);assert r.returncode==0 and not r.stderr and len(r.stdout)<65536
v=json.loads(r.stdout);v['sourceSHA256']=hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest();v['boundAuditReceiptSHA256']=hashlib.sha256(audit_raw).hexdigest()
with out.open('xb')as f:f.write((json.dumps(v,sort_keys=True,indent=2)+'\n').encode());f.flush();os.fsync(f.fileno())
print(json.dumps(v,sort_keys=True))
