#!/usr/bin/python3 -I -B
"""One narrow read-only WORK predicate observation, no strict retry or production mutation."""
import hashlib,json,os,pathlib,pwd,subprocess,time
TOOLS=pathlib.Path('/var/tmp/proofofwork-deploy/audit29-tools');CWD=pathlib.Path('/opt/proofofwork-api-stage-38ac6e2bff2a-20261003T042000Z');NODE='/opt/node-v24.18.0-linux-x64/bin/node'
VERIFY='8a569828272b10abc8848dd01678a1a3b45002acd489802f89b6e056de3e0c1e';PRIVATE='99cbe9cd118c63b08480efd28c2ae7c059b5204daef8db08b896a38fc791d515';READER='9278b81473c23a2c9d06c6b1306268c360539f833cdd7967b73fd99a35275b87'
LEAF=r"""
import {createProofIndexPool} from './server/db/postgres.mjs';
import {proofIndexTokenPayload,proofIndexSnapshotPayload,proofIndexWorkPrecisionV2MigrationReadiness,configuredWorkPrecisionV2ReaderPins,closeProofIndexReadPool}from'./server/db/proof-index-reader.mjs';
const WORK='d4e5ebf11d104d6a63fb74e42094364b25a5f7199a09e5c0e71408972466a8b8';
const count=v=>Array.isArray(v)?v.length:0,shape=v=>({returned:v!==null&&v!==undefined,source:v?.source??null,indexedThroughBlock:v?.indexedThroughBlock??null,indexedThroughBlockHash:v?.indexedThroughBlockHash??null,tokens:count(v?.tokens),holders:count(v?.holders),listings:count(v?.listings),mints:count(v?.mints),transfers:count(v?.transfers),snapshotId:v?.snapshotId??null});
let pool;try{pool=createProofIndexPool();const settings=(await pool.query("SELECT current_setting('transaction_read_only')AS read_only,current_setting('default_transaction_read_only')AS default_read_only")).rows[0];if(settings.read_only!=='on'||settings.default_read_only!=='on')throw Error('READONLY_NOT_ESTABLISHED');const summary=await proofIndexSnapshotPayload('livenet','workSummary'),unscoped=await proofIndexTokenPayload('livenet','',new URLSearchParams()),work=await proofIndexTokenPayload('livenet',WORK,new URLSearchParams({asset:WORK})),readiness=await proofIndexWorkPrecisionV2MigrationReadiness('livenet',configuredWorkPrecisionV2ReaderPins());const flags=Object.fromEntries(['active','ready','evidenceComplete','parityReady','pendingReady','replayReady','tipHeight','tipHash','pendingValidThrough'].map(k=>[k,readiness?.[k]??null]));flags.pendingReadinessDiagnostics=readiness?.pendingReadinessDiagnostics??null;console.log(JSON.stringify({schema:'audit30-scoped-work-predicate-readonly-v1',sqlReadOnly:settings,summary:shape(summary),unscoped:shape(unscoped),work:shape(work),readinessReturned:readiness!==null&&readiness!==undefined,readiness:flags,directDatabaseWrites:false,apiRequests:0,coreRequests:0}));}finally{await pool?.end();await closeProofIndexReadPool();}
"""
def main():
 assert os.geteuid()==os.getegid()==0;raw=(TOOLS/'private-verify.py').read_bytes();assert hashlib.sha256(raw).hexdigest()==VERIFY
 h={'__name__':'_frozen_private_verify','__file__':str(TOOLS/'private-verify.py')};exec(compile(raw,h['__file__'],'exec'),h);original=h['imported'](TOOLS/'private-env.py',PRIVATE);account=pwd.getpwnam('powadmin');before=original['proc_identity']('api',account)
 h['read'](CWD/'server/db/proof-index-reader.mjs',account.pw_uid,limit=4*1024**2,expected=READER);h['read'](pathlib.Path(NODE),limit=128*1024**2,expected='41a74efb34cbde5c7632cdac0cf8bd1a14d0b8d73dc1e82755014d9a9ce70f5c',group=0)
 blob=pathlib.Path('/proc/'+str(before['pid'])+'/environ').read_bytes();assert len(blob)<=2*1024**2;env=h['readonly_plan'](original,original['parse_env'](blob),'38ac6e2bff2a-20261003T042000Z',CWD,'http://127.0.0.1:18081');assert original['proc_identity']('api',account)==before;start=time.monotonic()
 r=subprocess.run([NODE,'--max-old-space-size=512','--input-type=module','-'],input=LEAF.encode(),cwd=CWD,env=env,user=account.pw_uid,group=account.pw_gid,extra_groups=[],capture_output=True,timeout=130,start_new_session=True)
 assert len(r.stdout)<=65536 and len(r.stderr)<=65536 and r.returncode==0 and not r.stderr;result=json.loads(r.stdout);assert result['sqlReadOnly']['read_only']=='on';assert original['proc_identity']('api',account)==before
 print(json.dumps({'schema':'audit30-strict-v2-narrow-work-predicate-read-v1','result':result,'elapsedSeconds':round(time.monotonic()-start,3),'sourceReaderSHA256':READER,'actualApiIdentityUnchanged':True,'productionMutation':False},sort_keys=True))
