import assert from'node:assert/strict';import fs from'node:fs';
import{validateArgv,validateEnvironment,parseFive,nativeMain,ADAPTER_SHA256,BINDING_SHA256,CUSTODY_SOURCE_SHA256}from'./pow-audit30-production-sixteen-native-caller-v1.mjs';
import{LIVE_FIVE}from'./pow-audit30-production-sixteen-adapter-v1.mjs';import{hash}from'./pow-audit30-production-sixteen-approval-binding-v2.mjs';
let assertions=0;const h='a'.repeat(64),apply=[h,h,h,h,'apply','none'],inverse=[h,h,h,h,'inverse','b'.repeat(64)];assert.equal(validateArgv(apply).operation,'apply');assert.equal(validateArgv(inverse).priorApplySHA256,'b'.repeat(64));assertions+=2;
for(const a of [[],[...apply,'extra'],[h,h,h,h,'apply',h],[h,h,h,h,'inverse','none'],[h,h,h,h,'both','none'],['false',...apply.slice(1)]]){assert.throws(()=>validateArgv(a));assertions++;}
validateEnvironment({PATH:'/usr/bin:/bin',TZ:'UTC'},108,112);assertions++;
for(const env of [{PGHOST:'/tmp/socket'},{PGPASSWORD:'test-synthetic'},{LD_PRELOAD:'/tmp/none'},{NODE_OPTIONS:'--eval x'},{DATABASE_URL:'synthetic-not-connected'}]){assert.throws(()=>validateEnvironment(env,108,112));assertions++;}
assert.throws(()=>validateEnvironment({},0,0));assertions++;
const text=Object.entries(LIVE_FIVE).map(([u,[pid,inv]])=>`Id=${u}\nLoadState=loaded\nActiveState=active\nMainPID=${pid}\nInvocationID=${inv}`).join('\n\n');assert.equal(Object.keys(parseFive(text)).length,5);assertions++;
for(const t of [text.replace('MainPID=2103760','MainPID=1'),text.replace('ActiveState=active','ActiveState=failed'),text+'\n\n'+text.split('\n\n')[0],text.split('\n\n').slice(1).join('\n\n'),text.replace('Id=bitcoind.service','Id=unknown.service'),text.replace('LoadState=loaded','LoadState=loaded\nLoadState=loaded')]){assert.throws(()=>parseFive(t));assertions++;}
assert.equal(hash(fs.readFileSync('/tmp/pow-audit30-production-sixteen-adapter-v1.mjs')),ADAPTER_SHA256);assert.equal(hash(fs.readFileSync('/tmp/pow-audit30-production-sixteen-approval-binding-v2.mjs')),BINDING_SHA256);assert.equal(hash(fs.readFileSync('/tmp/pow-audit30-private-sixteen-commit-inverse-adapter-v1.mjs')),CUSTODY_SOURCE_SHA256);assertions+=3;
await assert.rejects(nativeMain([]),/EXPLICIT_SINGLE_OPERATION_ARGV/);assertions++;
const source=fs.readFileSync('/tmp/pow-audit30-production-sixteen-native-caller-v1.mjs','utf8');assert.equal((source.match(/executeApprovedProduction\(client,/gu)||[]).length,1);assert.ok(source.includes("host:'/var/run/postgresql',port:5432"));assert.ok(!source.includes('setInterval'));assert.ok(source.includes('O_EXCL|fs.constants.O_NOFOLLOW'));assert.ok(source.includes('rootPostCoreWorkerObservationStillRequired:true'));assertions+=5;
console.log(JSON.stringify({passed:true,assertions,qualification:'Pure argv/role/environment/live-metadata/source binding and pre-client refusal fixtures. No generated approval or production files, network/database calls or COMMIT. Original2e9 transaction and private4e custody are reused; root typed-unit preparation, fresh-before/after480 and owned-unit stop remain mandatory concrete outer bindings.'}));
