#!/usr/bin/python3 -I -B
"""Creation-only local Action73/doc/public custody preparation. No repository mutations."""
import copy,hashlib,json,pathlib,datetime
T=pathlib.Path('/tmp');R=pathlib.Path('/home/sixer/ProofOfWork.Me');D='deploy/audit30/verification/'
def dump(name,j):
 b=(json.dumps(j,indent=2,sort_keys=True)+'\n').encode();p=T/name
 with p.open('xb')as f:f.write(b)
 return p
def data(p):return json.loads(pathlib.Path(p).read_bytes())
def meta(p):
 p=pathlib.Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def ref(p):
 q=meta(p);q['path']=D+pathlib.Path(p).name;return q
# Exact existing successful remote-reader receipts and public observations only.
u=data(T/'pow-audit30-item2-ui-evidence-stage-receipt-read-publication-native-v1.stdout');h=data(T/'pow-audit30-item2-ui-production-verified-v1/https-smoke-receipt.json');b=data(T/'pow-audit30-item2-browser-smoke-observed-v1.json');c=data(T/'pow-audit30-item2-ui-caddy-passive-native-v1.stdout')
assert u['ok'] and u['all818InodeMetadataUnchanged'] and u['allPriorRetainedRootsPreserved'] and u['source']['clean'] and u['source']['detached']
assert h['ok'] and h['archivedFilesChecked']==h['expectedPublicFiles']==810 and h['hostnameRootsChecked']==15 and h['apexRedirectVerified'] and h['finalLocalEvidenceReverified']
assert c['ok'] and c['beforeAfterEqual'] and c['caddyUnchangedFromBaseline'] and not c['rawConfigurationExported']
assert b['infinity']['completeHistoryLoaded'] and b['inception']['completeHistoryLoaded'] and b['infinity']['openTicketsDisplayed']==1 and b['infinity']['sealedTicketsDisplayed']==0 and not b['signingOrTransactionsPerformed']
assert h['manifestSha256']==u['activeManifest']['files']['activeManifest']['sha256']==c['observation']['activeManifest']['binding']['manifestSha256']
# Flatten public local smoke/provenance artifacts for the existing explicit /tmp copier contract.
for source,name in [(T/'pow-audit30-item2-ui-production-verified-v1/https-smoke-receipt.json','pow-audit30-item2-ui-https-smoke-exact-v1.json'),(T/'pow-audit30-item2-ui-production-verified-v1/manifest.provenance','pow-audit30-item2-ui-active-provenance-exact-v1.json')]:
 if not source.exists() and name.endswith('provenance-exact-v1.json'):
  matches=[p for p in (T/'pow-audit30-item2-ui-production-verified-v1').iterdir()if p.is_file() and p.stat().st_size==2513]
  assert matches and all(x.read_bytes()==matches[0].read_bytes()for x in matches);source=matches[0]
 raw=source.read_bytes();target=T/name
 if target.exists():assert target.read_bytes()==raw
 else:
  with target.open('xb')as f:f.write(raw)
files={}
def add(p,purpose='preserve-public-reviewed-source-or-actual-receipt'):
 p=pathlib.Path(p);assert p.parent==T and p.name.startswith('pow-audit30-')
 row={'original':meta(p),'proposedRepositoryPath':D+p.name,'purpose':purpose,'privateDataIncluded':False}
 old=files.get(row['proposedRepositoryPath']);assert old is None or old==row;files[row['proposedRepositoryPath']]=row
for row in data(T/'pow-audit30-item2-ui-preserved-public-source-manifest-v3.json')['sources']:
 assert meta(row['path'])['sha256']==row['sha256'];add(row['path'])
for row in data(T/'pow-audit30-item2-ui-caddy-passive-public-manifest-v1.json')['publicFiles']:add(row['source'])
for name in ['pow-audit30-item2-ui-preserved-public-source-manifest-v2.json','pow-audit30-item2-ui-preserved-public-source-manifest-v3.json','pow-audit30-item2-ui-caddy-passive-public-manifest-v1.json','pow-audit30-item2-browser-smoke-observed-v1.json','pow-audit30-item2-scoped-bond-ui-seal-qualification-v1.json','pow-audit30-item2-ui-https-smoke-exact-v1.json','pow-audit30-item2-ui-active-provenance-exact-v1.json']:
 add(T/name)
for prefix in ['pow-audit30-item2-ui-evidence-stage-stage-native-v3','pow-audit30-item2-ui-evidence-stage-source-native-v3','pow-audit30-item2-ui-evidence-stage-publication-native-v2','pow-audit30-item2-ui-evidence-stage-receipt-read-publication-native-v1','pow-audit30-item2-ui-caddy-passive-native-v1']:
 for suffix in ['stdout','stderr','json']:add(T/(prefix+'.'+suffix),'preserve-actual-root-owned-public-transport-or-bounded-receipt')
raw=(R/'audits/2026-10-02-audit30-remaining-phase-execution.evidence.json').read_bytes();old=json.loads(raw);assert len(old['actions'])==72 and hashlib.sha256(raw).hexdigest()=='2e89ebfe67d01fb412154205bc26a6e127e03e9d609ab6ef9b6e0c19468a4528'
at=h['finishedAt'];cc=copy.deepcopy(old['currentContinuation'])
ui={'status':'actual-production-published-and-verified','releaseId':h['releaseId'],'commit':h['commit'],'tree':h['tree'],'publishedAtUtc':'2026-10-03T20:58:18Z','publicationEvidence':ref(T/'pow-audit30-item2-ui-evidence-stage-publication-native-v2.stdout'),'closedReceiptEvidence':ref(T/'pow-audit30-item2-ui-evidence-stage-receipt-read-publication-native-v1.stdout'),'live':u['live'],'activeManifest':u['activeManifest'],'managedArchive':u['managedArchive'],'newRollbackRoot':u['newRollbackRoot'],'priorRetainedRoots':u['retainedRoots'],'stageReceipt':u['receiptProjections']['stage'],'sourceReceipt':u['receiptProjections']['source'],'publicationReceipt':u['receiptProjections']['publication'],'preservedInputFingerprint':u['preservedInputFingerprint'],'all818InodeMetadataUnchanged':True,'allPriorRetainedRootsPreserved':True,'packageManifestSha256':u['packageManifestSha256'],'source':u['source'],'privateTemporaryStages':u['privateTemporaryStages'],'stageAbsent':u['stage']['absent'],'managedUnits':u['states'],'https':h,'httpsEvidence':ref(T/'pow-audit30-item2-ui-https-smoke-exact-v1.json'),'browser':b,'browserEvidence':ref(T/'pow-audit30-item2-browser-smoke-observed-v1.json'),'caddyUnchanged':True,'caddyEvidence':ref(T/'pow-audit30-item2-ui-caddy-passive-native-v1.stdout'),'scopedBondUiQualification':ref(T/'pow-audit30-item2-scoped-bond-ui-seal-qualification-v1.json'),'capacityQualification':'The exact new-release full 453701632-byte copy is charged to its evidence-stage allocation under the unchanged 5 GiB gate. Global /var/tmp/proofofwork-deploy 5 GiB accounting remains separately enforced for 32 MiB receipt growth; root-filesystem 10 GiB free-space, 64 MiB growth and 128-free-inode reserves remain. No historical artifact move/deletion or limit reduction was performed.','qualification':'Actual16 source surfaces and matching active/archive provenance; HTTPS verifies 810 public files across 15 hostname roots plus apex redirect. The 54 NFT aliases are deliberately excluded by the original smoke verifier. Guest browser smoke observes complete scoped histories at later Core 969761; POWB Open 1/Sealed 0 does not infer a seal from a historical SealTX link. Native financial acceptance remains separately scoped at 969758. Signing/private wallet actions/explicit attachment rendering are excluded.'}
qual='Actual production API/mail and frontend publication/HTTPS/guest browser acceptance passed. Release-specific documentation, source custody, hygiene, commit, push and one release announcement/handoff remain; global migration, physical/PITR/capacity and custody/dependency work are separate.'
nextq='Preserve the exact final public receipts and source custody; append dated operational documentation, review final scope and semantic hygiene, run hygiene:fix then hygiene:check, commit and push with required trailers, publish and verify one release announcement, and record exact handoff. Human items 3–5 and their later global closure remain pending.'
for target in [cc['currentApiEvidence'],cc['userRemainingChecklist']['2']]:
 target.update({'acceptanceStatus':'production-api-mail-ui-passed-release-handoff-pending','actionOrdinal':73,'blockingCheck':None,'blockingCheckQualification':'The historical scratch capacity refusals remain dated Action72 evidence. The separately guarded evidence-stage/source/publication continuation succeeded without changing limits or deleting historical artifacts.','uiPublicationPerformed':True,'productionUiAcceptanceComplete':True,'productionApiMailAndUiAcceptanceComplete':True,'runtimeAcceptanceComplete':True,'uiAcceptance':copy.deepcopy(ui),'fullStrictStatus':'production-strict-v2-pass; node-cutover-complete; production-api-mail-ui-pass; release-handoff-pending','currentAcceptanceQualification':qual,'nextRequired':nextq,'overallApiAcceptance':False,'overallApiAcceptanceQualification':'The existing overall release checklist flag remains incomplete only pending release-specific repository and announcement handoff; actual production API/mail/UI acceptance is independently complete.','overallReleaseAcceptance':False})
 target['cutoverStatus'].update({'productionAndMailAndUiAcceptanceComplete':True,'qualification':qual,'qualificationObservedThroughUtc':at})
cc['atUtc']=cc['observedThroughUtc']=at;cc['statusQualification']=qual;cc['userRemainingChecklist']['2']['status']='in-progress'
a={'schema':'pow-audit30-action73-ui-publication-acceptance-v1','action':'Record actual evidence-stage/source provenance, guarded frontend publication and matching 810-file/15-root HTTPS plus guest browser acceptance. Preserve all earlier native/read/staging failures and every historical action. Current production API/mail/UI acceptance is complete; release-specific custody/documentation/hygiene/commit/push/announcement handoff remains pending.','atUtc':at,'observedThroughUtc':at,'status':'production-runtime-acceptance-complete-release-handoff-pending','productionCodeCutoverPerformed':True,'productionDataMutation':False,'uiPublicationPerformed':True,'postcutoverProductionStrictAcceptance':True,'productionPositiveWorkAcceptance':True,'productionScopedBondAcceptance':True,'productionMailRawHtmlAcceptance':True,'productionApiAndMailAcceptanceComplete':True,'productionUiAcceptanceComplete':True,'productionApiMailAndUiAcceptanceComplete':True,'runtimeAcceptanceComplete':True,'overallApiAcceptance':False,'overallReleaseAcceptance':False,'overallApiAcceptanceQualification':qual,'canonicalMailItem4Status':'complete','canonicalMailItem4Qualification':old['actions'][-1]['canonicalMailItem4Qualification'],'priorProductionAcceptanceActionOrdinal':72,'uiAcceptance':ui,'additionalDeletion':False,'automaticRetry':False,'historicalActionsPreserved':72,'humanToCanonicalRemainingMap':old['currentContinuation']['humanToCanonicalRemainingMap'],'nextRequired':nextq,'publicSourceCustodyAdded':[],'qualification':qual}
# Actual preserved receipt maps differ in their fixed leaf key; retain explicit accepted projections fromAction72 without fabricating values.
a['priorProductionAcceptanceEvidence']={'strictAccepted':old['actions'][-1]['productionAcceptanceAttempts']['strict']['acceptedReceipt'],'positiveAndScoped':copy.deepcopy(old['actions'][-1]['productionAcceptanceAttempts']['positiveWorkAndScopedBonds']),'mailAcceptedAggregate':copy.deepcopy(old['actions'][-1]['productionAcceptanceAttempts']['mailHttpsAndDerivedHtml']['acceptedAggregate'])}
q={'schema':'pow-audit30-action73-proposed-update-v1','status':'draft-not-applied','proposedActionOrdinal':73,'trackerMutationPerformed':False,'preparedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'rootReconciliationStatus':'machine-reconciled-awaiting-root-review','trackerPreimage':{'path':'audits/2026-10-02-audit30-remaining-phase-execution.evidence.json','bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'actionCount':72},'proposedAction':a,'proposedCurrentContinuation':cc,'preservation':{'all72OriginalActions':True,'allOriginalTopLevelFieldsExceptCurrentContinuationAndUpdatedAt':True,'humanItem1CompleteUnchanged':True,'humanItems3Through6Unchanged':True},'peerReviewQualification':'Root and source_release must review this exact draft before apply; this preparation makes no repository, production or Git change.'}
# Source inventory and actual outcome rows are explicitly public. Copying action draft itself is optional; include local preparer as reproducible public source.
add(T/'pow-audit30-action73-prepare-local-v1.py')
a['publicSourceCustodyAdded']=[{'originalPath':r['original']['path'],'repositoryPath':r['proposedRepositoryPath'],'bytes':r['original']['bytes'],'sha256':r['original']['sha256'],'purpose':r['purpose']}for r in sorted(files.values(),key=lambda x:x['proposedRepositoryPath'])]
dump('pow-audit30-action73-proposed-update-v1.json',q)
dump('pow-audit30-action73-proposed-public-custody-manifest-v1.json',{'schema':'pow-audit30-action73-proposed-public-custody-manifest-v1','members':sorted(files.values(),key=lambda x:x['proposedRepositoryPath']),'privateCapturesBodiesOrRawAddressesIncluded':False,'deletionRequested':False,'trackerMutationPerformed':False,'productionCalls':False,'qualification':'Public sources/typed contracts and actual bounded production receipts only. No bundles/binary archives/rawconfig/environment/mail bodies/screenshots are copied. Prepared sources do not establish extra execution outcomes.'})
print(json.dumps({'draft':meta(T/'pow-audit30-action73-proposed-update-v1.json'),'publicManifest':meta(T/'pow-audit30-action73-proposed-public-custody-manifest-v1.json'),'publicRows':len(files),'productionCalls':False,'repositoryMutations':False}))
