import hashlib,json,os,pathlib,shlex,subprocess,sys
source=pathlib.Path('/tmp/pow-audit30-stop-owned-38ac042000-shadow-v1.py').read_bytes();assert hashlib.sha256(source).hexdigest()=='dcc903303c48e5f7b8d78b466722988092b606b909d5ab0e0e47e6b35de57130'
reuse=pathlib.Path('/tmp/pow-audit30-shadow-capture-cache-reuse-v1.py').read_bytes();assert hashlib.sha256(reuse).hexdigest()=='9779f0da95707f175c2c8b7606c679a030d495ef53f506c137896e35e4aaa30a'
p=pathlib.Path('/tmp/pow-audit30-owned-38ac042000-shadow-stop-native-v1.json');assert not any(os.path.lexists(str(p)+x)for x in ['', '.stdout','.stderr'])
code="\nimport hashlib,json,pathlib,re,subprocess\nE={'PATH':'/usr/bin:/bin','LC_ALL':'C'};unit='proofofwork-audit30-candidate-full-ids-38ac6e2bff2a-20261003T042000Z-fence-diagnostic-v3.service'\nassert hashlib.sha256(SRC).hexdigest()==STOP_SHA and hashlib.sha256(REUSE).hexdigest()==REUSE_SHA\nn={'__name__':'_reviewed_exact_owned_stop','__file__':'/tmp/reviewed-stop-owned-38ac042000-shadow-v1.py'};exec(compile(SRC,n['__file__'],'exec'),n)\nhelper_bytes=n['read'](n['TOOLS']/'private-env.py',n['PINS']['private-env.py']);h={'__name__':'_exact_private_env','__file__':str(n['TOOLS']/'private-env.py')};exec(compile(helper_bytes,h['__file__'],'exec'),h)\ncompletion=json.loads(h['private_read'](str(n['ROOT']/'cli-fence-diagnostic-d7bbe914-v3-completed.json')));assert completion['schema']=='pow-audit30-cli-native-completed-v3'and completion['unit']==unit and completion['returncode']==0 and completion['stopped']is True and re.fullmatch('[0-9a-f]{32}',completion['invocationID'])\nz=subprocess.run(['/usr/bin/systemctl','show',unit,'--property=LoadState,ActiveState,MainPID,InvocationID'],env=E,capture_output=True,timeout=10);assert z.returncode==0 and not z.stderr;state=dict(x.split('=',1)for x in z.stdout.decode().splitlines()if '='in x);assert state['MainPID']=='0'and state['ActiveState']in ['inactive','failed'];assert(state['LoadState']=='not-found'and state['InvocationID']=='')or(state['LoadState']=='loaded'and state['InvocationID']==completion['invocationID'])\nr={'__name__':'_exact_reuse'};exec(compile(REUSE,'reviewed-reuse','exec'),r)\nbefore=n['live']();admission=r['admit_existing_capture_cache'](lambda p:h['private_read'](str(p)),helper_bytes,n['TOOLS']/'private-env.py');assert n['live']()==before\nstop=n['execute']();print(json.dumps({'schema':'pow-audit30-owned-38ac042000-shadow-stop-and-cli-state-v1','cliUnitStopped':True,'cliUnitState':state,'cliCompletion':completion,'existingCaptureCacheAdmission':admission,'stopResult':stop},sort_keys=True))\n"
ssh=['ssh','-i','/home/sixer/.ssh/proofofwork_node_ed25519','-o','BatchMode=yes','-o','IdentitiesOnly=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10','powadmin@65.108.122.87',shlex.join(['sudo','-n','/usr/bin/python3','-I','-B','-'])];r=subprocess.run(ssh,input=('SRC='+repr(source)+'\nREUSE='+repr(reuse)+'\nSTOP_SHA='+repr(hashlib.sha256(source).hexdigest())+'\nREUSE_SHA='+repr(hashlib.sha256(reuse).hexdigest())+'\n'+code).encode(),capture_output=True,timeout=600)
for ext,b in [('.stdout',r.stdout),('.stderr',r.stderr)]:
 with pathlib.Path(str(p)+ext).open('xb')as f:f.write(b);f.flush();os.fsync(f.fileno())
d=dict(schema='pow-audit30-owned-38ac042000-shadow-stop-native-transport-v1',returncode=r.returncode,sourceSHA256=hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),controllerSHA256=hashlib.sha256(source).hexdigest(),reuseGuardSHA256=hashlib.sha256(reuse).hexdigest(),stdoutSHA256=hashlib.sha256(r.stdout).hexdigest(),stderrSHA256=hashlib.sha256(r.stderr).hexdigest(),result=json.loads(r.stdout)if r.returncode==0 else None)
with p.open('xb')as f:f.write((json.dumps(d,sort_keys=True,indent=2)+'\n').encode());f.flush();os.fsync(f.fileno())
print(json.dumps(d,sort_keys=True));sys.exit(r.returncode)
