import assert from 'node:assert/strict';
import test from 'node:test';
import crypto from 'node:crypto';
import fs from 'node:fs';
import {assemble,authorities,parseInput} from './pow-audit30-onhost-math-plan-assemble-v1.mjs';
import * as O from './pow-audit30-transition-onhost-math-v2.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),a=authorities();
function fixture(){
 const rows=a.core.sampleRows.map(r=>({height:r.height,hash:r.hash}));
 const snapshot={height:969526,hash:rows[2].hash,transitionHeight:969526,transitionHash:rows[2].hash},fence='d9c08752be9e8e7c8d9ce4409b20496783901f116becbb26e205904dc676564b';
 const inputs=Object.fromEntries(O.INPUT_SUFFIXES.map((s,i)=>[s,{bytes:2,sha256:(i===1?'1':String(i+1)).repeat(64)}]));
 const base={schema:'pow-audit30-private-transition-prototype-plan-v1',privateJob:O.JOB,privateSocket:O.JOB+'/socket',privatePort:55432,sourceDatabase:'proof_indexer',network:'livenet',checkpoint:snapshot,sourceFenceSha256:fence,sampleRows:rows,columns:a.columns,precisionMarkerJsonbSendSha256:'b'.repeat(64)};
 const checkpoint={network:'livenet',height:969526,hash:rows[2].hash,sourceFenceSha256:fence,sampleRowKeysSha256:sha(JSON.stringify(rows))};
 const context={schema:'pow-audit30-stream-native-oracle-inputs-v1',privateJob:O.JOB,evidenceDirectory:O.EVIDENCE,prefix:'native',basePlan:base,envelope:O.DEFAULT_ENVELOPE,sourceFenceSha256:fence,sourceSnapshot:snapshot,sampleRows:rows,fullColumns:a.columns,markerJsonbSendSha256:'b'.repeat(64),sourceSha256:inputs['.copy'].sha256,reconstructedSha256:inputs['.reconstructed.copy'].sha256,fullByteEquality:true,bindings:O.INPUT_SUFFIXES.filter(s=>s!=='.context.json').map(s=>({fileName:'native'+s,bytes:inputs[s].bytes,sha256:inputs[s].sha256})),precisionPins:'Separate source-reviewed immutable-marker/arithmetic operator; not invented by codec',mathAccepted:false,allHistoricalReplay:false};
 return {schema:'pow-audit30-onhost-math-safe-input-census-v1',context,columns:a.columns,checkpoint,inputs,sourceCopyCompletionSha256:'dc9e158445be2a176ef683ae7b3b5df40a44480f77ef9a57def85826d0225ff1',sourceCopyManifestSha256:'e904b0379dd6c80f68eebbb556b5bd5caa8619aa79df89f03ed16ebbeb6db977',streamCompletedSha256:'c'.repeat(64),streamIntentSha256:'d'.repeat(64),nodeMetadata:a.tools.nodeMetadata,attestorMetadata:a.tools.attestorMetadata,publisherMetadata:a.tools.publisherMetadata,liveFive:Object.fromEntries(['bitcoind.service','electrs.service','postgresql@16-main.service','proofofwork-api.service','proofofwork-indexer-worker.service'].map(k=>[k,{MainPID:'1',InvocationID:'a'.repeat(32)}]))};
}
test('actual code inventory13/source SQL/reference pins and exact relocation',()=>{assert.equal(Object.keys(a.pins).length,13);assert.equal(a.pins['server/sql/proof-indexer-v1.sql'],'830970ee14618a6356b0f7acebe2e188dbdced589c8eb9f1c53677d92ada5987');assert.equal(a.columns[23].name,'payload');assert.equal(a.columns[25].name,'work_token_state_model');assert.equal(a.layoutAdmission.nativeCaptureSha256,'69cf431cbede11d4867a85c8611ad932bc125d1c9da1560120ca6a20c4dfabac');});
test('valid metadata sample deterministic canonical plan/request only; no data proof',()=>{const c=fixture(),x=assemble(c),y=assemble(structuredClone(c));assert.deepEqual(x.planRaw,y.planRaw);assert.deepEqual(x.requestRaw,y.requestRaw);assert.equal(x.request.schema,'pow-audit30-onhost-math-managed-request-v3');assert.equal(x.request.mathPlanSha256,sha(x.planRaw));assert.equal(x.request.sourceCopyCompletionSha256,c.sourceCopyCompletionSha256);assert.equal(x.plan.historicalPlan.precisionPins.activationHeight,960601);assert.equal(x.planRaw.at(-1),125);assert.equal(x.requestRaw.at(-1),125);});
test('historical sample-key order restored despite canonical outer hash/height sorting',()=>{const p=assemble(fixture()).plan;const transport=O.historicalTransportPlan(JSON.parse(O.canonical(p)));assert.equal(sha(JSON.stringify(transport.sampleRows)),transport.checkpoint.sampleRowKeysSha256);assert.equal(Object.keys(transport.sampleRows[0])[0],'height');});
test('wrong actual completion and manifest raw pins rejected',()=>{for(const k of ['sourceCopyCompletionSha256','sourceCopyManifestSha256']){const c=fixture();c[k]='f'.repeat(64);assert.throws(()=>assemble(c));}});
test('wrong/missing schema or extra safe-census fields refused',()=>{for(const change of [c=>c.schema='wrong',c=>delete c.context,c=>c.extra=true]){const c=fixture();change(c);assert.throws(()=>assemble(c));}});
test('historical physical layout only; wrong order/name/OID/null model refused',()=>{for(const change of [c=>[c.columns[23],c.columns[25]]=[c.columns[25],c.columns[23]],c=>c.columns[0].name='wrong',c=>c.columns[1].typeOid='23',c=>c.columns.pop()]){const c=structuredClone(fixture());change(c);assert.throws(()=>assemble(c));}});
test('wrong checkpoint height/hash/key encoding/source fence refused',()=>{for(const [k,v]of [['height',969527],['hash','f'.repeat(64)],['sourceFenceSha256','f'.repeat(64)],['sampleRowKeysSha256','f'.repeat(64)],['network','testnet']]){const c=structuredClone(fixture());c.checkpoint[k]=v;assert.throws(()=>assemble(c));}});
test('sample order/height/hash drift versus separate Core witness refused',()=>{for(const change of [c=>c.context.sampleRows.reverse(),c=>c.context.sampleRows[1].height=960602,c=>c.context.sampleRows[1].hash='f'.repeat(64)]){const c=structuredClone(fixture());change(c);assert.throws(()=>assemble(c));}});
test('raw metadata/reconstruction/bytecap/extra suffix refusing actual operator predicates',()=>{for(const change of [c=>c.inputs['.copy'].bytes=64*1024**2+1,c=>c.inputs['.copy'].bytes=true,c=>c.inputs['.reconstructed.copy'].sha256='f'.repeat(64),c=>c.inputs['.context.json'].bytes=0,c=>c.inputs['.context.json'].extra=true,c=>delete c.inputs['.marker.copy'],c=>c.inputs['.other']={bytes:2,sha256:'f'.repeat(64)}]){const c=structuredClone(fixture());change(c);assert.throws(()=>assemble(c));}});
test('context producer cannot claim math acceptance or broaden envelope',()=>{for(const change of [c=>c.context.mathAccepted=true,c=>c.context.allHistoricalReplay=true,c=>c.context.fullByteEquality=false,c=>c.context.envelope.rowBytes*=2,c=>c.context.precisionPins={}]){const c=structuredClone(fixture());change(c);assert.throws(()=>assemble(c));}});
test('native private-job/socket/port/source database cannot redirect',()=>{for(const [k,v]of [['privateJob','/data/other'],['privateSocket','/run/postgresql'],['privatePort',5432],['sourceDatabase','postgres'],['network','testnet']]){const c=structuredClone(fixture());c.context.basePlan[k]=v;assert.throws(()=>assemble(c));}});
test('metadata input bindings and marker send hash exact',()=>{const c=structuredClone(fixture());c.context.bindings[0].sha256='f'.repeat(64);assert.throws(()=>assemble(c));const d=structuredClone(fixture());d.context.basePlan.precisionMarkerJsonbSendSha256='f'.repeat(64);assert.throws(()=>assemble(d));});
test('live identities exactpositive strings, fixed five names only',()=>{for(const change of [c=>delete c.liveFive['bitcoind.service'],c=>c.liveFive['other']={MainPID:'1',InvocationID:'a'.repeat(32)},c=>c.liveFive['bitcoind.service'].MainPID='0',c=>c.liveFive['bitcoind.service'].MainPID=1,c=>c.liveFive['bitcoind.service'].InvocationID='b',c=>c.liveFive['bitcoind.service'].extra=true]){const c=structuredClone(fixture());change(c);assert.throws(()=>assemble(c));}});
test('raw input canonical hash-bound no LF or duplicate fields',()=>{const c=fixture(),raw=Buffer.from(O.canonical(c));assert.deepEqual(parseInput(raw,sha(raw)),c);for(const b of [Buffer.concat([raw,Buffer.from('\n')]),Buffer.from('{"schema":1,"schema":2}'),Buffer.from(JSON.stringify(c,null,2))])assert.throws(()=>parseInput(b,sha(b)));assert.throws(()=>parseInput(raw,'f'.repeat(64)));});
test('fixture output carries hashes/metadata, never copy or marker value bytes',()=>{const x=assemble(fixture());assert.deepEqual(Object.keys(x.plan.inputs).sort(),O.INPUT_SUFFIXES.toSorted());assert.equal(typeof x.plan.historicalPlan.markerJsonbSendSha256,'string');assert.equal('markerValue'in x.plan,false);assert.equal('body'in x.plan,false);assert.equal('copyBase64'in x.plan,false);});

test('frozen native Node/attestor/publisher complete metadata cannot be omitted or altered',()=>{for(const k of ['nodeMetadata','attestorMetadata','publisherMetadata']){const c=structuredClone(fixture());c[k]={};assert.throws(()=>assemble(c));const d=structuredClone(fixture());d[k].ino='0';assert.throws(()=>assemble(d));}});
