import assert from 'node:assert/strict';import {readFile,writeFile,unlink} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const p='/tmp/pow-audit30-mail-projection-focused-leaf-v5.mjs',raw=await readFile(p,'utf8'),test='/tmp/pow-audit30-mail-projection-focused-test-local-v5.mjs';
const fixed='/usr/local/lib/proofofwork-audit30-mail-projection-focused-v5';const local='/home/sixer/ProofOfWork.Me';assert.equal(raw.split(fixed).length-1,2);await writeFile(test,raw.replaceAll(fixed,local),{flag:'wx',mode:0o600});
try{
const {summarize,readMailOnly,PRODUCTION_IDENTITY_SQL,validateProductionIdentity}=await import(pathToFileURL(test));const {proofIndexCanonicalMailProjectionParity:parity}=await import(pathToFileURL(local+'/server/proof-index-mail-projection.mjs'));const known=Array.from({length:16},(_,i)=>(i+1).toString(16).padStart(64,'0'));const events=known.map(txid=>({network:'livenet',txid,protocol:'pwm1',kind:'mail',valid:true,amount_sats:'1',data_bytes:5,event_time:null,payload:{body:' SECRET \n',subject:'keep'},status:'confirmed'}));const mail=known.map(txid=>({network:'livenet',txid,status:'confirmed',amount_sats:'1',data_bytes:5,event_time:null,body_text:'SECRET',message:{body:' SECRET \n',subject:'keep'},subject:'keep'}));let assertions=0;
const s=summarize(parity({eventRows:events,mailRows:mail,transactionRows:[]}),known);assert.equal(s.exactKnownSixteen,true);assert.equal(s.allMismatchesBodyOnly,true);assert.equal(s.fieldHistogram.body_text,16);assert.ok(!JSON.stringify(s).includes('SECRET'));assertions+=4;
const nullMail=structuredClone(mail);nullMail[0].body_text=null;assert.equal(summarize(parity({eventRows:events,mailRows:nullMail,transactionRows:[]}),known).exactKnownSixteen,true);assertions++;
const nonbody=structuredClone(mail);nonbody[0].subject='changed';assert.equal(summarize(parity({eventRows:events,mailRows:nonbody,transactionRows:[]}),known).allMismatchesBodyOnly,false);assertions++;
const incomplete=parity({eventRows:events,mailRows:mail,transactionRows:[]});incomplete.mismatchedCount=21;const q=summarize(incomplete,known);assert.equal(q.mismatchSampleComplete,false);assert.equal(q.exactKnownSixteen,false);assertions+=2;
const invalid=parity({eventRows:events,mailRows:mail,transactionRows:[]});invalid.mismatchedSample[0].fields=['PRIVATE'];assert.throws(()=>summarize(invalid,known));assertions++;
const productionIdentity={dataDirectory:'/var/lib/postgresql/16/main',socket:'/var/run/postgresql',listenAddresses:'localhost',port:'5432',readOnly:'off',checksums:'on',user:'postgres',database:'proof_indexer',serverAddress:null};const queries=[];let n=0;const c={query:async(sql,args)=>{queries.push({sql,args});if(sql===PRODUCTION_IDENTITY_SQL)return{rows:[{value:productionIdentity}]};if(sql.includes('current_setting'))return{rows:[{read_only:'on',snapshot:'s'}]};if(sql.startsWith('SELECT event'))return{rows:events};if(sql.startsWith('SELECT mail'))return{rows:mail};if(sql.startsWith('SELECT transaction'))return{rows:[]};return{rows:[]};}};const read=await readMailOnly(c);assert.deepEqual(read.productionDatabaseIdentity,productionIdentity);assert.equal(queries.filter(q=>q.sql===PRODUCTION_IDENTITY_SQL).length,1);const {SQL}=await import(pathToFileURL('/tmp/pow-audit30-mail-body-repair-rehearsal-v2.mjs'));assert.equal(PRODUCTION_IDENTITY_SQL,SQL.identity);assertions+=3;assert.equal(read.population.eventRows,16);assert.equal(read.parity.mismatchedCount,16);assert.equal(queries[0].sql,'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');assert.equal(queries.at(-1).sql,'ROLLBACK');assert.ok(queries[1].sql.includes("statement_timeout='20s'")&&queries[1].sql.includes("lock_timeout='3s'"));assertions+=5;
for(const change of [v=>v.secret='forbidden',v=>v.user='powadmin',v=>v.socket='/tmp/socket',v=>v.dataDirectory='/data/audit30/cluster',v=>v.port='55432']){const v=structuredClone(productionIdentity);change(v);assert.throws(()=>validateProductionIdentity(v),/DB_IDENTITY_SCOPE/);assertions++;}
const failureQueries=[];await assert.rejects(()=>readMailOnly({query:async(sql)=>{failureQueries.push(sql);if(sql.includes('current_setting'))throw Error('PRIVATE');return{rows:[]};}}));assert.equal(failureQueries.at(-1),'ROLLBACK');assertions+=2;
console.log(JSON.stringify({ok:true,assertions,qualification:'Local pure projection/closed sanitizer and fake client transaction contract; no PG/API/Core calls.'}));
}finally{await unlink(test);}
