import hashlib,json,os,pathlib,shlex,subprocess
src=pathlib.Path('/tmp/pow-audit30-candidate-bond-paging-engine.mjs').read_bytes();assert hashlib.sha256(src).hexdigest()=='174626efbddc3e2d4f2b363c39992038628d3277babb7560f0f6b5084bbe4991'
unit='proofofwork-audit30-candidate-bond-pages-38ac-v1.service'
code="import hashlib,os,subprocess,json\nenv={'PATH':'/usr/bin:/bin','LC_ALL':'C'}\nnode='/opt/node-v24.18.0-linux-x64/bin/node'\nassert hashlib.sha256(open(node,'rb').read()).hexdigest()=='41a74efb34cbde5c7632cdac0cf8bd1a14d0b8d73dc1e82755014d9a9ce70f5c'\nr=subprocess.run(['/usr/bin/systemctl','show',"+repr(unit)+",'--property=LoadState','--value'],env=env,capture_output=True,timeout=10)\nassert r.returncode==0 and r.stdout.strip()==b'not-found'\nargv="+repr(['/usr/bin/systemd-run','--quiet','--wait','--pipe','--unit='+unit,'--service-type=exec','--property=User=root','--property=Group=root','--property=RuntimeMaxSec=5min','--property=TimeoutStopSec=5s','--property=KillMode=control-group','--property=MemoryMax=1G','--property=MemorySwapMax=0','--property=CPUQuota=50%','--property=TasksMax=32','--property=UMask=0077','--property=ProtectSystem=strict','--property=ProtectHome=yes','--property=PrivateTmp=yes','--property=PrivateDevices=yes','--property=PrivateIPC=yes','--property=NoNewPrivileges=yes','/usr/bin/env','-i','PATH=/usr/bin:/bin','LC_ALL=C', '/opt/node-v24.18.0-linux-x64/bin/node','--max-old-space-size=512','--input-type=module','--eval',src.decode()])+"\nr=subprocess.run(argv,env=env,capture_output=True,timeout=310)\nassert len(r.stdout)<65536 and len(r.stderr)<65536\nprint(json.dumps({'returncode':r.returncode,'stdout':r.stdout.decode(),'stderrBytes':len(r.stderr),'stderrSHA256':hashlib.sha256(r.stderr).hexdigest(),'unit':"+repr(unit)+"},sort_keys=True))\n"
ssh=['ssh','-i','/home/sixer/.ssh/proofofwork_node_ed25519','-o','BatchMode=yes','-o','IdentitiesOnly=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10','powadmin@65.108.122.87',shlex.join(['sudo','-n','/usr/bin/python3','-I','-B','-'])]
r=subprocess.run(ssh,input=code.encode(),capture_output=True,timeout=330)
out=pathlib.Path('/tmp/pow-audit30-candidate-bond-paging-native-38ac-v1.json');data={'transportReturncode':r.returncode,'stdoutBytes':len(r.stdout),'stdoutSHA256':hashlib.sha256(r.stdout).hexdigest(),'stderrBytes':len(r.stderr),'stderrSHA256':hashlib.sha256(r.stderr).hexdigest(),'engineSHA256':hashlib.sha256(src).hexdigest()}
if r.returncode==0:
 v=json.loads(r.stdout);data['native']=v;data['result']=json.loads(v.pop('stdout'))if v['stdout']else None
with out.open('xb')as f:f.write((json.dumps(data,sort_keys=True,indent=2)+'\n').encode());f.flush();os.fsync(f.fileno())
print(json.dumps(data,sort_keys=True))
