#!/usr/bin/env python3
"""Actual readonly full ID CLI, using existing source-pinned readonly-plan helper; no timer changes."""
import hashlib,json,os,pathlib,shlex,subprocess,sys
RELEASE='38ac6e2bff2a-20261003T040230Z'
CODE=r'''
import ctypes,hashlib,json,os,pathlib,pwd,resource
RELEASE='38ac6e2bff2a-20261003T040230Z';TOOLS=pathlib.Path('/var/tmp/proofofwork-deploy/audit29-tools');cwd=pathlib.Path('/opt/proofofwork-api-stage-'+RELEASE)
s=(TOOLS/'private-verify.py').lstat();assert s.st_uid==s.st_gid==0 and s.st_nlink==1 and s.st_mode&0o777==0o600 and (TOOLS/'private-verify.py').resolve()==TOOLS/'private-verify.py';raw=(TOOLS/'private-verify.py').read_bytes();assert hashlib.sha256(raw).hexdigest()=='8a569828272b10abc8848dd01678a1a3b45002acd489802f89b6e056de3e0c1e';V={'__name__':'_phase6_readonly_cli','__file__':str(TOOLS/'private-verify.py')};exec(compile(raw,str(TOOLS/'private-verify.py'),'exec'),V)
original=V['imported'](TOOLS/'private-env.py','99cbe9cd118c63b08480efd28c2ae7c059b5204daef8db08b896a38fc791d515');account=pwd.getpwnam('powadmin');assert original['safe_candidate'](RELEASE,account)==str(cwd);manifest=json.loads(original['private_read'](original['runroot'](RELEASE)+'/capture.json'));assert manifest['processes']['api']['identityFinal']==original['proc_identity']('api',account)
blob=original['private_read'](original['runroot'](RELEASE)+'/api.environ');assert hashlib.sha256(blob).hexdigest()==manifest['processes']['api']['environmentSha256'];env=V['readonly_plan'](original,original['parse_env'](blob),RELEASE,cwd,'http://127.0.0.1:18081');assert env[b'POW_ID_AUDIT_WRITE_REPORTS']==b'0' and env[b'POW_ID_AUDIT_RETRIES']==b'0';assert hashlib.sha256(V['read'](cwd/'scripts/audit-id-registry.mjs',account.pw_uid,limit=2*1024**2)).hexdigest()==ID_SOURCE_SHA
assert V['runtime_binary']()['sha256']=='41a74efb34cbde5c7632cdac0cf8bd1a14d0b8d73dc1e82755014d9a9ce70f5c';os.chdir(cwd);os.umask(0o077);resource.setrlimit(resource.RLIMIT_CORE,(0,0));assert ctypes.CDLL(None,use_errno=True).prctl(38,1,0,0,0)==0;os.setgroups([]);os.setgid(account.pw_gid);os.setuid(account.pw_uid);os.execve('/opt/node-v24.18.0-linux-x64/bin/node',['/opt/node-v24.18.0-linux-x64/bin/node','--max-old-space-size=1024',str(cwd/'scripts/audit-id-registry.mjs')],env)
'''
def main(out):
 src=pathlib.Path('/home/sixer/ProofOfWork.Me/scripts/audit-id-registry.mjs').read_bytes();srcsha=hashlib.sha256(src).hexdigest();code='ID_SOURCE_SHA='+repr(srcsha)+'\n'+CODE;unit='proofofwork-audit30-candidate-full-ids-'+RELEASE+'-v1.service';argv=['/usr/bin/systemd-run','--quiet','--wait','--pipe','--unit='+unit,'--service-type=exec','--property=User=root','--property=Group=root','--property=RuntimeMaxSec=12min','--property=TimeoutStopSec=15s','--property=KillMode=control-group','--property=MemoryMax=2G','--property=MemorySwapMax=0','--property=CPUQuota=50%','--property=TasksMax=32','--property=UMask=0077','/usr/bin/python3','-I','-B','-c',code]
 ssh=['ssh','-i','/home/sixer/.ssh/proofofwork_node_ed25519','-o','BatchMode=yes','-o','IdentitiesOnly=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10','powadmin@65.108.122.87',shlex.join(['sudo','-n',*argv])];r=subprocess.run(ssh,capture_output=True,timeout=750)
 for suffix,raw in [('.stdout',r.stdout),('.stderr',r.stderr)]:
  with pathlib.Path(str(out)+suffix).open('xb')as f:f.write(raw);f.flush();os.fsync(f.fileno())
 text=r.stdout.decode('utf-8','replace');counts={label:int(__import__('re').search(__import__('re').escape(label)+r': (\d+)',text).group(1))for label in ['Fetched transactions','Covered confirmed registry transactions','Covered pending registry transactions','Confirmed winners','Pending candidates']if __import__('re').search(__import__('re').escape(label)+r': (\d+)',text)};report=dict(schema='pow-audit30-candidate-full-id-cli-receipt-v1',returncode=r.returncode,complete=r.returncode==0 and 'Canonical lifecycle parity: verified against exact Core-ordered chain replay'in text and len(counts)==5,counts=counts,unit=unit,sourceSHA256=hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),auditScriptSHA256=srcsha,stdoutBytes=len(r.stdout),stdoutSHA256=hashlib.sha256(r.stdout).hexdigest(),stderrBytes=len(r.stderr),stderrSHA256=hashlib.sha256(r.stderr).hexdigest(),productionMutation=False,timerChanges=False)
 with out.open('xb')as f:f.write((json.dumps(report,sort_keys=True)+'\n').encode());f.flush();os.fsync(f.fileno())
 print(json.dumps(report,sort_keys=True));return r.returncode
if __name__=='__main__':sys.exit(main(pathlib.Path(sys.argv[1])))
