import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateReviewProofs,validateFreshStatelessFence,buildAdmission,executeApprovedProduction,EA56_SHA256,ORIGINAL_ENGINE_SHA256,TARGETS_SHA256,EXPECTED_SAVED_RECEIPTS,EXPECTED_ORIGINAL_FAILURE,RECONCILIATION_SHA256,RESTORED_MAIL}from'./pow-audit30-production-sixteen-adapter-v2.mjs';
import {encoded,hash,PLAN_SHA256,MANIFEST_SHA256,TEMPLATE_SHA256,WORKER_GUARD_SHA256}from'./pow-audit30-production-sixteen-approval-binding-v2.mjs';
const projection=fs.readFileSync('/tmp/pow-audit30-mail-projection-focused-native-v4.stdout'),worker=fs.readFileSync('/tmp/pow-audit30-repair-first-worker-observation-native-v1.stdout'),w=JSON.parse(worker),now=Date.parse(w.atUtc)+1000;
// Synthetic future private COMMIT/inverse proof only in test memory. Actual
// private proof is still a mandatory native acceptance before any human question.
const fp=(count=1)=>({count,logical_bytes:'1',sha256:'c'.repeat(64)});
const priv={schema:'pow-audit30-private-sixteen-readonly-finalization-completed-v1',status:'passed',crossTransactionFullMailFingerprintRestored:true,sealedSourceFullHashVerifiedBeforeStart:true,sealedSourceFullHashVerifiedAtStop:true,privateClusterStopped:true,offlinePrivatePagesChecked:true,liveServicesUnchanged:true,backupWindowRecheckedAtStop:true,sourceAndAllEvidenceRetained:true,originalAttemptRemainsFailed:true,operationalReadinessTwoLegitimateInvalidations:true,rootPrivateMathFullAllocationCharged:true,productionMutation:false,sealedSourceStarted:false,automaticRetry:false,writerInvoked:false,applyInvoked:false,inverseInvoked:false,operationalEpochRewind:false,reconciliationReceiptSha256:RECONCILIATION_SHA256,streamCompletedSha256:'974e16cfb288e19e7320fa87687d32cff65b2a58296b4e94893ddbdfaea3c841',mathCompletedSha256:'3d65f98e03aa341eed849d1506339ccd66af443d6fcf9cf33e794cd4073edcaf',savedReceiptBindings:structuredClone(EXPECTED_SAVED_RECEIPTS),originalFailureBindings:structuredClone(EXPECTED_ORIGINAL_FAILURE),currentReadOnlyState:{currentCompleteMailFingerprint:RESTORED_MAIL,currentJournalFingerprint:{queue:fp(0),shards:fp(128),meta:fp()},samePrivateDatabaseIdentity:true,explicitReadOnlyTransaction:true,currentSavedFence:{canonicalBlock:{height:969526,hash:'00000000000000000001c495201991943ae88860aeaca7db34c37e210e765ee0'},confirmedTransactionMaxHeight:969511,transitionMaxHeight:969526,transitionMaxHash:'00000000000000000001c495201991943ae88860aeaca7db34c37e210e765ee0',precisionMarkerStatus:'complete',precisionActivationHeight:'960601'}},adapterProof:JSON.parse(fs.readFileSync('/tmp/pow-audit30-private-sixteen-reconcile-native-v1.stdout')).adapterProof};
// Preserve actual metadata integer spelling when constructing IN-MEMORY test JSON.
const bytes=x=>Buffer.from(encoded(x).replace(/"(ctimeNs|mtimeNs)":"([0-9]+)"/gu,'"$1":$2'));const a=p=>({privateCommitInverseProofReceiptSHA256:hash(bytes(p)),freshMailProjectionReceiptSHA256:hash(projection),writerTemplateSHA256:TEMPLATE_SHA256});const fence=x=>({sourceSHA256:WORKER_GUARD_SHA256,raw:bytes(x),rawSHA256:hash(bytes(x))});let assertions=0;
assert.equal(validateReviewProofs(a(priv),bytes(priv),projection).projection.freshMailProjection.parity.mismatchedCount,16);assertions++;
for(const k of ['crossTransactionFullMailFingerprintRestored','sealedSourceFullHashVerifiedAtStop','privateClusterStopped','offlinePrivatePagesChecked']){const x=structuredClone(priv);x[k]=false;assert.throws(()=>validateReviewProofs(a(x),bytes(x),projection));assertions++;}
for(const k of ['separateInverseCommitAcknowledged','bodyPreimagesRestored']){const x=structuredClone(priv);x.adapterProof[k]=false;assert.throws(()=>validateReviewProofs(a(x),bytes(x),projection));assertions++;}
for(const change of [x=>x.schema='pow-audit30-private-sixteen-supervision-completed-v1',x=>x.originalAttemptRemainsFailed=false,x=>x.writerInvoked=true,x=>x.applyInvoked=true,x=>x.inverseInvoked=true,x=>x.reconciliationReceiptSha256='0'.repeat(64),x=>x.streamCompletedSha256='0'.repeat(64),x=>x.mathCompletedSha256='0'.repeat(64),x=>x.savedReceiptBindings['apply-completed.json'].sha256='0'.repeat(64),x=>x.originalFailureBindings.failed.metadata.inode++,x=>x.savedReceiptBindings['apply-commit-intent.json'].metadata.ctimeNs=(BigInt(x.savedReceiptBindings['apply-commit-intent.json'].metadata.ctimeNs)+1n).toString(),x=>delete x.savedReceiptBindings['proof-completed.json'],x=>x.currentReadOnlyState.explicitReadOnlyTransaction=false,x=>x.currentReadOnlyState.samePrivateDatabaseIdentity=false,x=>x.currentReadOnlyState.currentCompleteMailFingerprint.sha256='0'.repeat(64),x=>x.currentReadOnlyState.currentJournalFingerprint.queue.count=1,x=>x.currentReadOnlyState.currentSavedFence.transitionMaxHash='0'.repeat(64),x=>x.adapterProof.privateJob='/another-clone',x=>x.adapterProof.applyReceiptSHA256='a'.repeat(64)]){const x=structuredClone(priv);change(x);assert.throws(()=>validateReviewProofs(a(x),bytes(x),projection));assertions++;}
// A rounded JSON.stringify timestamp or a string masquerading as the original
// numeric timestamp cannot satisfy the exact saved-custody binding.
for(const bad of [Buffer.from(encoded(priv)),Buffer.from(bytes(priv).toString().replace('1791013637273970168','1791013637273970169'))]){assert.throws(()=>validateReviewProofs({...a(priv),privateCommitInverseProofReceiptSHA256:hash(bad)},bad,projection));assertions++;}
const p=JSON.parse(projection);for(const change of [x=>x.freshMailProjection.parity.fieldHistogram={subject:16},x=>x.freshMailProjection.parity.missingCount=1,x=>x.freshMailProjection.parity.exactKnownSixteen=false,x=>x.freshMailProjection.parity.mismatchedCount=17]){const x=structuredClone(p);change(x);const ap={...a(priv),freshMailProjectionReceiptSHA256:hash(bytes(x))};assert.throws(()=>validateReviewProofs(ap,bytes(priv),bytes(x)));assertions++;}
assert.equal(validateFreshStatelessFence(fence(w),now).coreTip.height,969692);assertions++;
for(const change of [x=>x.atUtc=new Date(now-120001).toISOString(),x=>x.liveServices['proofofwork-indexer-worker.service'].MainPID='1',x=>x.observations.checkpoint.indexed_through_block=962934,x=>x.observations.worker.backfillPhases=[{kind:'combined',sources:['block-scan','registry-history']}],x=>x.runtimeAllowlisted.POW_INDEX_REPAIR_CANONICAL_MAIL_PROJECTION='1',x=>x.observations.worker.activePwtRangeReplay=true,x=>x.observations.rebuild.active=true,x=>x.sourceSha256['scripts/run-proof-indexer-worker.mjs']='0'.repeat(64)]){const x=structuredClone(w);change(x);assert.throws(()=>validateFreshStatelessFence(fence(x),now));assertions++;}
assert.throws(()=>validateFreshStatelessFence({...fence(w),sourceSHA256:'0'.repeat(64)},now));assertions++;
const ids=JSON.parse(fs.readFileSync('/tmp/pow-audit30-mail-native-progress-v2-1.json')).files['proposed-body-only-manifest.json'].value.targets.map(t=>t.txid),plan={targets:ids.map(txid=>({txid}))},approval={readinessClosureSHA256:'c'.repeat(64),expectedDatabaseIdentity:{database:'proof_indexer'},receiptSHA256:'d'.repeat(64)},gen='e'.repeat(64),ad=buildAdmission(approval,plan,gen,'apply'),inv=buildAdmission(approval,plan,gen,'inverse','f'.repeat(64));assert.equal(ad.targetTxidSetSHA256,TARGETS_SHA256);assert.equal(ad.engineSHA256,inv.engineSHA256);assert.equal(inv.priorAcknowledgedApplyReceiptSHA256,'f'.repeat(64));assertions+=3;
await assert.rejects(executeApprovedProduction(null,{},{}),/EXISTING_NATIVE_CLIENT_CUSTODY_AND_FENCES_REQUIRED/);assertions++;
let queries=0;await assert.rejects(executeApprovedProduction({query:()=>{queries++;}}, {},{durable:async()=>{},fence:async()=>{}}),/ORIGINAL_PRIVATE_PLAN_AND_ENGINE_PIN/);assert.equal(queries,0);assertions+=2;
console.log(JSON.stringify({passed:true,assertions,qualification:'Actual public projection/worker captures validate closed predicates at their observation times; future private proof/approval uses in-memory synthetic objects only. No DB/approval/generated production file/native execution. The original writer26 tests cover its transaction, unknown-COMMIT and inverse. Required trusted root IO hooks remain an execution admission, not implemented as a new supervisor.'}));
