// Historical audit reproduction; local source only. Never signs, broadcasts or persists a transaction.
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { compareBoostCanonicalEvents } from '../server/boost-projection.mjs';
import { proofIndexEventParticipantsForItem, proofIndexEventRefsForItem, proofIndexCanonicalEventRelationParity } from '../server/proof-index-event-relations.mjs';
const root=new URL('../', import.meta.url).pathname;
const paths=['scripts/backfill-proof-indexer.mjs','server/proof-api.mjs','server/proof-index-event-relations.mjs','server/db/proof-index-reader.mjs','server/work-amo-v5-raw.mjs'];
const files=Object.fromEntries(paths.map(p=>[p,fs.readFileSync(root+p,'utf8')]));
const extract=(text,name)=>{const start=text.indexOf(`function ${name}(`); if(start<0)throw Error(name);const next=text.slice(start+1).search(/\n(?:async )?function |\nexport (?:async )?function /u);return text.slice(start,next<0?undefined:start+1+next);};
const backfill=files[paths[0]], api=files[paths[1]];
const context={NETWORK:'livenet',BOOST_POST_MAX_CHARS:140,BOOST_ACTION_REGISTRY_FEE_SATS:546,Buffer,Date,BigInt,Number,String,Object,Array,Math,JSON,Map,Set};
vm.createContext(context);
for(const name of ['normalizedText','normalizedLowerText','satsFromVoutValue','satsFromVout','addressFromVout','paymentOutputsBeforeProtocol','senderAddressFromTx','firstInputPrevoutScriptpubkey','blockEventTime','baseProtocolItem','boostTxidText','boostSignalSats','boostRegistryFeePaid','validBoostRegistryItem','invalidProtocolItem','boostItemFromMessage'])vm.runInContext(extract(backfill,name),context);
const author='1BPVvi1GK4QkfqFMU4jHGjsQjyGwjJJJ7x';
const outsider='19JE7LS6TtQ4uSxu6ivJVZRiJyXXe8qEG3';
const target='1'.repeat(64), transferTxid='2'.repeat(64);
const carrier=`pwb1:t:${target}:${outsider}`;
const raw={txid:transferTxid,height:966100,_powBlockIndex:1,blocktime:1788885000,confirmations:1,vin:[{prevout:{scriptpubkey_address:outsider,scriptpubkey:'0014'+'00'.repeat(20),value:1000}}],vout:[{n:0,scriptpubkey_address:outsider,scriptpubkey:'0014'+'00'.repeat(20),value:546},{n:1,scriptpubkey:'6a',value:0}]};
context.tx=raw;context.message={text:carrier,prefix:'pwb1:',voutIndex:1};
const parsed=vm.runInContext('boostItemFromMessage(tx,message)[0]',context);
context.compareBoostCanonicalEvents=compareBoostCanonicalEvents;
context.BOOST_INDEX_EVENT_KINDS=new Set(['boost-post','boost-hide','boost-transfer']);context.BOOST_VISIBLE_EVENT_KINDS=new Set(['boost-post','boost-reply','boost-reboost']);
for(const name of ['boostHexTxid','boostAddress','boostPostTxid'])vm.runInContext(extract(api,name),context);
vm.runInContext(extract(api,'boostOwnershipState'),context);
const post={kind:'boost-post',protocol:'pwb1',txid:target,boostTxid:target,confirmed:true,valid:true,blockHeight:966099,blockIndex:0,protocolVout:1,recordOrdinal:0,eventId:'1',authorAddress:author};
context.events=[post,parsed];const ownership=vm.runInContext('boostOwnershipState(events).states.get(events[0].txid)',context);
const unfollow={kind:'boost-unfollow',protocol:'pwb1',action:'unfollow',confirmed:true,valid:true,authorAddress:author,followerAddress:author,targetAddress:outsider,targetId:'fixture-target-id',recipients:[{address:'fixture-registry',amountSats:'546'}]};
const participants=proofIndexEventParticipantsForItem(unfollow),refs=proofIndexEventRefsForItem(unfollow);
const sharedParity=proofIndexCanonicalEventRelationParity({eventRows:[{event_id:'1',status:'confirmed',payload:unfollow}],participantRows:participants.map(p=>({...p,event_id:'1'})),refRows:refs.map(r=>({...r,event_id:'1'}))});
const result={scope:'Local production-source extraction; synthetic transaction is never signed, submitted, or persisted. Source call-chain inspection supplements parser/reducer execution.',sourceHashes:Object.fromEntries(paths.map(p=>[p,crypto.createHash('sha256').update(files[p]).digest('hex')])),outsiderTransfer:{author,outsider,carrier,onlyPaymentAddress:raw.vout[0].scriptpubkey_address,parsedKind:parsed.kind,parsedValid:parsed.valid,parsedAmountSats:parsed.amountSats,parsedSenderAddress:parsed.senderAddress,parsedRegistryFeeSats:parsed.registryFeeSats,ownerAfterReducer:ownership.ownerAddress},unfollowTarget:{targetAddress:unfollow.targetAddress,participants,refs,targetIncluded:participants.some(p=>p.address===unfollow.targetAddress),sharedParityReady:sharedParity.ready},productionPath:{parse:'backfill-proof-indexer.mjs:4251,4391-4409',replayBinding:'backfill-proof-indexer.mjs:22603-22741 preserves Boost semantic kind, payload, sets replay valid',persistenceGate:'backfill-proof-indexer.mjs:5969-5972 bound item returns directly',participantWriter:'backfill-proof-indexer.mjs:13512-13536 calls shared extractor',reader:'proof-index-reader.mjs:37319-37412 preserves payload and relational status',feed:'proof-api.mjs:51853-51867 reads complete PWB history, filters valid and builds ownership',ownership:'proof-api.mjs:51333-51343 replaces owner from transfer without comparing actor'},economicQualification:'Canonical evaluatePwb remains zero-economic-delta placeholder; this reproduction establishes application state/display validation gap, not changed WORK/ID/credit balances or canonical network value.'};
console.log(JSON.stringify(result,null,2));
