export const MAX_PAGE_BYTES: number;
export const MAX_PAGE_DRAFTS: number;
export type PagesNetwork = "livenet" | "testnet" | "testnet4";
export type PagesIdentity = { id: string; ownerAddress: string; receiveAddress: string };
export type PagesOrigin = { txid: string; sha256: string; confirmed: boolean; sender: string; modified: boolean };
export type PageDraft = { id: string; title: string; html: string; updatedAt: number; origin?: PagesOrigin };
export type PagesDraftStore = { version: 1; activeId: string; drafts: PageDraft[] };
export function pageByteLength(html: string): number;
export function pagesStorageKey(network: PagesNetwork, address?: string): string;
export function validatePageHtml(html: unknown): string;
export function decodePageFile(bytes: Uint8Array): string;
export function escapePageHtml(value: unknown): string;
export function pageFileName(title: string): string;
export function pageTemplateHtml(title?: string, app?: boolean): string;
export function identityCardHtml(identity: PagesIdentity): string;
export function insertPageMarkup(html: string, markup: string, selection?: { start: number; end: number }): string;
export function validatePagesDrafts(value: unknown): PagesDraftStore;
export const PAGES_APP_CSP: string;
export function pagesAppPreviewHtml(html: string, document: Document): string;
